#!/usr/bin/env bash
# Generated by build.sh from install.sh.in and lib/01-manifests.sh. Edit those, never this file.
# ABOUTME: Installation script for agent-sessions (ags command, with cs compatibility)
# ABOUTME: Installs binaries, hooks, skills, and shell completions
# ABOUTME: build.sh splices lib/01-manifests.sh in at the marker to write install.sh.

set -euo pipefail

# Colors - Claude warm palette (rust → orange → gold)
# Disable colors if NO_COLOR is set (https://no-color.org) or not a TTY
if [[ -n "${NO_COLOR:-}" ]] || [[ ! -t 1 ]]; then
    RED=''
    GREEN=''
    YELLOW=''
    ORANGE=''
    GOLD=''
    RUST=''
    COMMENT=''
    BOLD=''
    NC=''
else
    RED='\033[38;2;239;83;80m'        # #ef5350 - warm red
    GREEN='\033[38;2;139;195;74m'     # #8bc34a - vibrant green
    YELLOW='\033[38;2;255;183;77m'    # #ffb74d - warm amber
    ORANGE='\033[38;2;255;138;101m'   # #ff8a65 - coral orange
    GOLD='\033[38;2;255;193;7m'       # #ffc107 - golden
    RUST='\033[38;2;230;74;25m'       # #e64a19 - terracotta
    COMMENT='\033[38;2;161;136;127m'  # #a1887f - warm taupe
    BOLD='\033[1m'
    NC='\033[0m'
fi

error() {
    echo -e "${RED}Error: $1${NC}" >&2
    exit 1
}

info() {
    echo -e "${GREEN}$1${NC}"
}

warn() {
    echo -e "${YELLOW}$1${NC}"
}

installed() {
    echo -e "   ${COMMENT}Installed${NC} $1 ${COMMENT}→${NC} ${GOLD}$2${NC}"
}

show_banner() {
    local GT="${ORANGE}agent-sessions"
    echo ""
    echo -e "   ${RUST}╭───────────────────────╮${NC}"
    echo -e "   ${RUST}│${NC}    ${GT}${NC}    ${GOLD}│${NC}"
    echo -e "   ${GOLD}╰───────────────────────╯${NC}"
    echo ""
}

# Configuration
INSTALL_DIR="${HOME}/.local/bin"
# The global cs installation belongs to the stable tool. Only an alias already
# owned by this installer may be refreshed. setup.sh deploys to a separate HOME.
if { [ -e "$INSTALL_DIR/cs" ] || [ -L "$INSTALL_DIR/cs" ]; } \
    && { [ ! -L "$INSTALL_DIR/cs" ] || [ "$(readlink "$INSTALL_DIR/cs")" != ags ]; }; then
    error "Existing cs installation detected. Run sh setup.sh for an isolated ags install."
fi
HOOKS_PARENT_DIR="${HOME}/.claude/hooks"
HOOKS_DIR="${HOOKS_PARENT_DIR}/cs"
COMMANDS_DIR="${HOME}/.claude/commands"
BASH_COMPLETION_DIR="${HOME}/.bash_completion.d"
ZSH_COMPLETION_DIR="${HOME}/.zsh/completions"
# Detect existing zsh completion dir from user's fpath config
if [ -f "$HOME/.zshrc" ]; then
    _detected_dir=$(grep -oE 'fpath.*~/\.zsh/completions?' "$HOME/.zshrc" 2>/dev/null | grep -oE '~/\.zsh/completions?' | head -1 | sed "s|~|$HOME|") || true
    if [ -n "$_detected_dir" ]; then
        ZSH_COMPLETION_DIR="$_detected_dir"
    fi
fi
CLAUDE_SETTINGS="${HOME}/.claude/settings.json"
SESSIONS_DIR="${HOME}/.claude-sessions"
# Omitted selection reuses the previous install; old installs retain both.
INSTALL_CONFIG="$INSTALL_DIR/.cs-install-engines"
INSTALL_ENGINES="${CS_INSTALL_ENGINES:-}"
if [ -z "$INSTALL_ENGINES" ] && [ -f "$INSTALL_CONFIG" ]; then
    INSTALL_ENGINES=$(cat "$INSTALL_CONFIG")
fi
INSTALL_ENGINES="${INSTALL_ENGINES:-claude,codex}"
case "$INSTALL_ENGINES" in
    claude|codex|claude,codex|codex,claude) ;;
    *) error "CS_INSTALL_ENGINES must be claude, codex, or claude,codex" ;;
esac
_install_has_engine() { [[ ",$INSTALL_ENGINES," == *,$1,* ]]; }

# Payload ref: `cs -update` pins this to the release tag (v<version>) so the
# downloaded scripts/hooks match the verified installer; a fresh curl|bash
# install defaults to main.
REPO_URL="https://raw.githubusercontent.com/hex/claude-sessions/${CS_INSTALL_REF:-main}"
RELEASES_URL="https://github.com/hex/claude-sessions/releases/download"
AGS_URL="${REPO_URL}/bin/ags"
AGS_SECRETS_URL="${REPO_URL}/bin/ags-secrets"
AGS_CODEX_THREAD_URL="${REPO_URL}/bin/ags-codex-thread"
AGS_STATUSLINE_URL="${REPO_URL}/bin/ags-statusline"
AGS_SUBAGENT_STATUSLINE_URL="${REPO_URL}/bin/ags-subagent-statusline"

# ---- lib/01-manifests.sh (spliced by build.sh) ----
# Files a past version deployed into the hooks directory and this one does not:
# retired hooks, and any support file that went with them. Removed on install
# and on uninstall, wherever an older cs left them.
# install.sh and run_uninstall both clean these up.
# When retiring a hook in a release, add its filename here.
RETIRED_HOOKS=(
    narrative-precompact.sh   # retired: PreCompact cannot inject context (no hookSpecificOutput/additionalContext); Stop reminder covers capture
    discovery-commits.sh      # renamed to autosave-commits.sh (general all-file crash recovery, not discoveries-specific)
    discoveries-reminder.sh   # retired: session narrative moved to .cs/memory/narrative.md (native lazy-load, no size budget)
    discoveries-archiver.sh   # retired in v2026.4.7 (archive flow replaced by size-budget compaction)
    aboutme-prereader.sh      # retired: source-file ABOUTME-header nudge experiment
    gotcha-prewriter.sh       # retired: brief pre-write gotcha-surfacing experiment; approach was rethought
    aboutme-validator.sh      # retired: never-shipped PostToolUse-on-Write experiment from a feature branch that registered the hook in settings.json without the file ever landing in source
    command-tracker.sh        # retired: CLI command capture; @-included payload did not influence model behaviour at a rate justifying its context cost
    cs-logo.png               # retired: the icon source for the finished-turn notification, which the iTerm2 sidebar owns now (not a hook; a file the hooks directory carried)
    files-scan.sh             # retired: workspace file indexer for .cs/files.md (assumption that the agent can't introspect file sizes has expired)
    files-context.sh          # retired: PreToolUse:Read context injector that surfaced files.md token estimates
    changes-tracker.sh        # retired: PostToolUse change log re-narrating git history into .cs/changes.md; git log/diff/status is authoritative
    artifact-tracker.sh       # retired: PreToolUse:Write redirect was inert (updatedInput path rewrite is not honored by the harness); tracking removed entirely
    prose-lint.sh             # retired with the `ags -lint` verb it called; MUST stay listed, because a deployed copy calling the removed verb reads error()'s exit 1 as "violations found" and blocks every turn-end
    memory-index-guard.sh     # moved into the sweep skill (sweep/scripts/), so the guard travels with the skill to every engine
)

# Hook scripts cs ships; deployed to ~/.claude/hooks/cs/ and registered in
# settings.json.
CS_HOOKS=(
    session-start.sh
    autosave-commits.sh
    narrative-reminder.sh
    session-end.sh
    subagent-context.sh
    tool-failure-logger.sh
    session-auto-approve.sh
    bash-logger.sh
    scope-prompt.sh
)

# Files under hooks/ that the hooks source, or that cs points other tools at,
# rather than files Claude Code invokes as hooks. Deployed and removed alongside
# the hooks, never registered against an event. The prompt-rewriter scripts are
# reached through $EDITOR, not through any hook event.
CS_HOOK_LIBS=(
    cs-resolve.sh
    cs-shared.sh
    prompt-rewriter.sh
    prompt-rewriter-model.sh
    prompt-rewriter-vendor.sh
)

# Slash commands earlier versions deployed to ~/.claude/commands/. cs ships
# none now: they became skills of the same name, the one format every engine
# reads. install.sh and run_uninstall delete these files; a command left
# beside its skill would answer the same /name twice.
RETIRED_COMMANDS=(
    summary.md
    checkpoint.md
    sweep.md
    wrap.md
)

# Skills cs ships; each deploys as <skills dir>/<name>/SKILL.md, for Claude
# under ~/.claude/skills and for Codex under $CODEX_HOME/skills (default
# ~/.codex/skills). Both engines get the same files.
CS_SKILLS=(
    store-secret
    prose-hygiene
    rotate
    finish
    feature
    write-as-me
    checkpoint
    summary
    sweep
    wrap
)

# Skills retired or renamed in past versions but possibly still installed from
# older cs versions. install.sh and run_uninstall both delete these directories.
# When retiring or renaming a skill in a release, add its OLD name here: a skill
# directory left behind keeps answering its slash command forever, and nothing
# else ever removes it.
#
# Only the Claude skills directory is swept. Every name below retired before
# cs deployed skills to Codex, so in a Codex skills directory it can only be
# the user's own skill. A skill retired after shipping to Codex must also be
# removed from there.
#
# Do not add a doctor row for a leftover directory; it cannot report one. The
# only cs that could still hold it is one older than the retirement, and that cs
# has no entry here to check against; the upgrade that gives it the entry is the
# same install that deletes the directory. So the row would warn about a state
# it can never observe.
RETIRED_SKILLS=(
    voice   # renamed to write-as-me; Claude Code 2.1.227 ships a built-in /voice (Toggle voice mode)
    merge   # replaced by finish: integrate and report, never remove
    cs-hint # a mod (deployed under skills/ like every mod): the hint line under the prompt, retired
    cs-rotate # a mod: renamed to cs, cs's in-session mod (the rotate band, forced rotation, the wrap key)
)

# Support files skills ship beyond SKILL.md, as skills/<skill>/<path> entries.
# Files under scripts/ are executables; agents/openai.yaml is Codex's
# per-skill settings, which Claude ignores.
CS_SKILL_FILES=(
    write-as-me/scripts/build-corpus.sh
    finish/scripts/finish.sh
    finish/agents/openai.yaml   # Codex ignores disable-model-invocation; this is its switch
    sweep/scripts/memory-index-guard.sh
)

# Mods cs ships: Claude Code function-hooks plugins, deployed file by file as
# ~/.claude/skills/<mod>/<path> (the mod's bun tests stay in the checkout).
CS_MOD_FILES=(
    cs/.claude-plugin/plugin.json
    cs/hooks/hooks.json
    cs/hooks/register.tsx
    cs-update/.claude-plugin/plugin.json
    cs-update/hooks/hooks.json
    cs-update/hooks/register.tsx
)

# Remove a hook registration from any event in a settings JSON string,
# matching either path spelling; drops wrappers that empty out. Prints the
# updated JSON.
_strip_hook_registration() {
    local settings="$1" p="$2" t="$3"
    echo "$settings" | jq --arg p "$p" --arg t "$t" '
        if .hooks then
            .hooks |= with_entries(
                .value |= (
                    map(.hooks |= map(select(.command != $p and .command != $t)))
                    | map(select(.hooks | length > 0))
                )
            )
        else . end
    '
}

# The SessionStart hook ags registers for Codex: Codex runs the command through
# a shell, so a path outside the plain-word alphabet is single-quoted.
_codex_hook_command() {  # ags_path
    case "$1" in
        *[!A-Za-z0-9_./+-]*)
            printf "'%s' -codex-hook session-start" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")" ;;
        *) printf '%s -codex-hook session-start' "$1" ;;
    esac
}

# Codex skips a hook, silently, until config.toml trusts it: a table
# [hooks.state."<hooks.json path>:session_start:<group>:<handler>"] holding the
# sha256 of the handler group's definition, as compact sorted-key JSON with
# Codex's defaults filled in. ags writes that hash in the same step that
# registers its hook, so the hook runs without a review prompt.
_codex_hook_trust_hash() {  # command
    local json
    json=$(jq -ncS --arg c "$1" \
        '{event_name: "session_start", hooks: [{async: false, command: $c, timeout: 600, type: "command"}]}' \
        | tr -d '\n') || return 1
    if command -v sha256sum >/dev/null 2>&1; then
        printf '%s' "$json" | sha256sum | cut -c1-64
    else
        printf '%s' "$json" | shasum -a 256 | cut -c1-64
    fi
}

# A config.toml rewrite: drop the trust table for each listed key, then rename
# trust tables for SessionStart groups past a removed one down by one index
# (shift_from, empty for none), keeping every other line as it was.
_codex_trust_tables_edit() {  # config, hooks_file, shift_from, keys...
    local config="$1" file="$2" shift_from="$3" tmp
    shift 3
    [ -f "$config" ] || return 0
    tmp=$(mktemp "$config.ags.XXXXXX") || return 1
    awk -v prefix="[hooks.state.\"$file:session_start:" -v shift_from="$shift_from" -v drops="$(printf '%s\n' "$@")" '
        BEGIN {
            n = split(drops, list, "\n")
            for (i = 1; i <= n; i++) if (list[i] != "") drop["[hooks.state.\"" list[i] "\"]"] = 1
        }
        # Blank lines wait for the next line that survives, so a dropped table
        # takes its separating blank with it and trailing blanks never pile up.
        /^[[:space:]]*$/ { if (!skip) blanks++; next }
        $0 in drop { skip = 1; next }
        skip && /^[[:space:]]*\[/ { skip = 0 }
        skip { next }
        { while (blanks > 0) { print ""; blanks-- } }
        shift_from != "" && index($0, prefix) == 1 {
            rest = substr($0, length(prefix) + 1)
            split(rest, parts, ":")
            if (parts[1] ~ /^[0-9]+$/ && parts[1] + 0 > shift_from + 0) {
                print prefix (parts[1] - 1) substr(rest, length(parts[1]) + 1)
                next
            }
        }
        { print }
    ' "$config" > "$tmp" || { rm -f "$tmp"; return 1; }
    mv "$tmp" "$config" || { rm -f "$tmp"; return 1; }
}

# Index of ags's own SessionStart group in a hooks.json document, or nothing.
_codex_hook_group_index() {  # hooks.json content
    printf '%s' "$1" | jq -r '
        [(.hooks.SessionStart // [])
         | to_entries[]
         | select(any(.value.hooks[]?; (.command // "") | endswith(" -codex-hook session-start")))
         | .key] | first // empty'
}

# Register ags's SessionStart hook in <codex_dir>/hooks.json and trust it in
# <codex_dir>/config.toml. A reinstall replaces the group in place and a first
# install appends it, so the user's own groups keep their indices, and with
# them their trust. A hooks.json that is not valid JSON is left alone.
_codex_hooks_register() {  # codex_dir, command
    local dir="$1" cmd="$2" file="$1/hooks.json" config="$1/config.toml"
    local doc index tmp hash key
    case "$file" in *'"'*|*\\*) return 1 ;; esac
    if [ -f "$file" ]; then
        doc=$(cat "$file") || return 1
        printf '%s' "$doc" | jq -e 'type == "object"' >/dev/null 2>&1 || return 1
    else
        doc='{}'
    fi
    index=$(_codex_hook_group_index "$doc")
    doc=$(printf '%s' "$doc" | jq --arg c "$cmd" --arg i "$index" '
        {hooks: [{type: "command", command: $c}]} as $ours
        | .hooks = (.hooks // {})
        | .hooks.SessionStart = (.hooks.SessionStart // [])
        | if $i == "" then .hooks.SessionStart += [$ours]
          else .hooks.SessionStart[($i | tonumber)] = $ours end') || return 1
    [ -n "$index" ] || index=$(printf '%s' "$doc" | jq '.hooks.SessionStart | length - 1')
    mkdir -p "$dir" || return 1
    tmp=$(mktemp "$file.ags.XXXXXX") || return 1
    printf '%s\n' "$doc" > "$tmp" && chmod 600 "$tmp" && mv "$tmp" "$file" || { rm -f "$tmp"; return 1; }
    hash=$(_codex_hook_trust_hash "$cmd") || return 1
    key="$file:session_start:$index:0"
    _codex_trust_tables_edit "$config" "$file" "" "$key" || return 1
    [ -f "$config" ] || { : > "$config" && chmod 600 "$config"; } || return 1
    if [ -s "$config" ]; then printf '\n' >> "$config" || return 1; fi
    printf '[hooks.state."%s"]\ntrusted_hash = "sha256:%s"\n' "$key" "$hash" >> "$config"
}

# Remove ags's SessionStart group and its trust table. Groups after it move up
# one index, so their trust tables are renamed to match. A hooks.json left with
# nothing in it is removed.
_codex_hooks_unregister() {  # codex_dir
    local dir="$1" file="$1/hooks.json" config="$1/config.toml" doc index tmp
    [ -f "$file" ] || return 0
    doc=$(cat "$file") || return 1
    index=$(_codex_hook_group_index "$doc" 2>/dev/null) || return 1
    [ -n "$index" ] || return 0
    doc=$(printf '%s' "$doc" | jq --argjson i "$index" '
        .hooks.SessionStart |= (to_entries | map(select(.key != $i)) | map(.value))
        | if .hooks.SessionStart == [] then del(.hooks.SessionStart) else . end
        | if .hooks == {} then del(.hooks) else . end') || return 1
    if [ "$doc" = '{}' ]; then
        rm -f "$file" || return 1
    else
        tmp=$(mktemp "$file.ags.XXXXXX") || return 1
        printf '%s\n' "$doc" > "$tmp" && chmod 600 "$tmp" && mv "$tmp" "$file" || { rm -f "$tmp"; return 1; }
    fi
    _codex_trust_tables_edit "$config" "$file" "$index" "$file:session_start:$index:0"
}
# ---- end lib/01-manifests.sh ----

# Everything that lands in HOOKS_DIR, for the copy and cleanup loops. The
# libraries go first: a web install that stops partway then leaves new
# libraries under old hooks, which still run, rather than new hooks without
# the library they source.
CS_HOOK_FILES=("${CS_HOOK_LIBS[@]}" "${CS_HOOKS[@]}")

# Completion URLs for web install
COMPLETION_BASH_URL="${REPO_URL}/completions/ags.bash"
COMPLETION_ZSH_URL="${REPO_URL}/completions/_ags"

# Minisign public key for verifying signed releases
CS_SIGN_PUBKEY="RWQvs3IVdvrS8PJs0V0gwdJGPw/x5waQ6z6iqPQm90JfpxfcsSy9b9Vo"

# Detect if running from cloned repo or web install
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd)"
if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/bin/ags" ]; then
    # Running from cloned repo
    AGS_SOURCE="$SCRIPT_DIR/bin/ags"
    HOOKS_SOURCE="$SCRIPT_DIR/hooks"
    INSTALL_METHOD="local"
else
    # Running from web (curl | bash)
    INSTALL_METHOD="web"
fi

# Check for Claude Code
if _install_has_engine claude && ! command -v claude >/dev/null 2>&1; then
    warn "Claude Code (claude) not found in PATH"
    warn "Install Claude Code for Claude sessions, or use --engine codex with Codex CLI"
    warn "Visit: https://github.com/anthropics/claude-code"
    echo ""
fi

# Show banner
show_banner

# Create install directory if needed
mkdir -p "$INSTALL_DIR"

# Install canonical ags command. The cs name remains a symlink for existing
# shell history, scripts and integrations; both names run the same entrypoint.
installed "ags" "$INSTALL_DIR/ags"

if [ "$INSTALL_METHOD" = "local" ]; then
    # Install from local clone
    cp "$AGS_SOURCE" "$INSTALL_DIR/ags"
else
    # Download from GitHub
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$AGS_URL" -o "$INSTALL_DIR/ags" || error "Failed to download ags script"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$AGS_URL" -O "$INSTALL_DIR/ags" || error "Failed to download ags script"
    else
        error "Neither curl nor wget found. Please install one of them."
    fi
fi

chmod +x "$INSTALL_DIR/ags"
ln -sfn ags "$INSTALL_DIR/cs"

# Install cs-secrets utility
installed "ags-secrets" "$INSTALL_DIR/ags-secrets"

if [ "$INSTALL_METHOD" = "local" ]; then
    cp "$SCRIPT_DIR/bin/ags-secrets" "$INSTALL_DIR/ags-secrets"
else
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$AGS_SECRETS_URL" -o "$INSTALL_DIR/ags-secrets" || error "Failed to download ags-secrets"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$AGS_SECRETS_URL" -O "$INSTALL_DIR/ags-secrets" || error "Failed to download ags-secrets"
    fi
fi

chmod +x "$INSTALL_DIR/ags-secrets"
ln -sfn ags-secrets "$INSTALL_DIR/cs-secrets"

if _install_has_engine codex; then
# Install the optional Codex runtime's no-model thread bootstrap helper.
# Python is required only when a user selects the Codex engine.
installed "ags-codex-thread" "$INSTALL_DIR/ags-codex-thread"
if [ "$INSTALL_METHOD" = "local" ]; then
    cp "$SCRIPT_DIR/bin/ags-codex-thread" "$INSTALL_DIR/ags-codex-thread"
elif command -v curl >/dev/null 2>&1; then
    curl -fsSL "$AGS_CODEX_THREAD_URL" -o "$INSTALL_DIR/ags-codex-thread" || error "Failed to download ags-codex-thread"
else
    wget -q "$AGS_CODEX_THREAD_URL" -O "$INSTALL_DIR/ags-codex-thread" || error "Failed to download ags-codex-thread"
fi
chmod +x "$INSTALL_DIR/ags-codex-thread"
ln -sfn ags-codex-thread "$INSTALL_DIR/cs-codex-thread"

fi

if _install_has_engine claude; then
# Install ags-statusline (Claude Code status line)
installed "ags-statusline" "$INSTALL_DIR/ags-statusline"

if [ "$INSTALL_METHOD" = "local" ]; then
    cp "$SCRIPT_DIR/bin/ags-statusline" "$INSTALL_DIR/ags-statusline"
else
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$AGS_STATUSLINE_URL" -o "$INSTALL_DIR/ags-statusline" || error "Failed to download ags-statusline"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$AGS_STATUSLINE_URL" -O "$INSTALL_DIR/ags-statusline" || error "Failed to download ags-statusline"
    fi
fi

chmod +x "$INSTALL_DIR/ags-statusline"
ln -sfn ags-statusline "$INSTALL_DIR/cs-statusline"

# Install ags-subagent-statusline (Claude Code agent-panel rows). It sources
# ags-statusline for the shared palette, so the two must land in the same dir.
installed "ags-subagent-statusline" "$INSTALL_DIR/ags-subagent-statusline"

if [ "$INSTALL_METHOD" = "local" ]; then
    cp "$SCRIPT_DIR/bin/ags-subagent-statusline" "$INSTALL_DIR/ags-subagent-statusline"
else
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$AGS_SUBAGENT_STATUSLINE_URL" -o "$INSTALL_DIR/ags-subagent-statusline" || error "Failed to download ags-subagent-statusline"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$AGS_SUBAGENT_STATUSLINE_URL" -O "$INSTALL_DIR/ags-subagent-statusline" || error "Failed to download ags-subagent-statusline"
    fi
fi

chmod +x "$INSTALL_DIR/ags-subagent-statusline"
ln -sfn ags-subagent-statusline "$INSTALL_DIR/cs-subagent-statusline"

fi

# Install ags-tui (interactive session manager), with the old cs-tui alias.
#
# bin/cs-tui is a gitignored build artifact and nothing regenerates it: build.sh
# assembles bin/cs from lib/ and has no TUI arm, while `cargo build --release`
# writes to tui/target/release/. Installing bin/cs-tui unconditionally therefore
# ships whatever binary happens to be sitting there, which has silently deployed
# a picker weeks older than the release being installed. A version check cannot
# catch it either: the picker carries no version of its own, so `cs -version`
# reads correct while the picker is stale. Prefer whichever of the two is newer.
_cs_tui_src="$SCRIPT_DIR/bin/ags-tui"
_cs_tui_built="$SCRIPT_DIR/tui/target/release/ags-tui"
if [ ! -f "$_cs_tui_src" ] && [ -f "$SCRIPT_DIR/bin/cs-tui" ]; then
    _cs_tui_src="$SCRIPT_DIR/bin/cs-tui"
fi
if [ ! -f "$_cs_tui_built" ] && [ -f "$SCRIPT_DIR/tui/target/release/cs-tui" ]; then
    _cs_tui_built="$SCRIPT_DIR/tui/target/release/cs-tui"
fi
if [ -f "$_cs_tui_built" ] && { [ ! -f "$_cs_tui_src" ] || [ "$_cs_tui_built" -nt "$_cs_tui_src" ]; }; then
    _cs_tui_src="$_cs_tui_built"
fi
if [ "$INSTALL_METHOD" = "local" ] && [ -f "$_cs_tui_src" ]; then
    installed "ags-tui" "$INSTALL_DIR/ags-tui"
    cp "$_cs_tui_src" "$INSTALL_DIR/ags-tui"
    chmod +x "$INSTALL_DIR/ags-tui"
elif [ "$INSTALL_METHOD" = "web" ]; then
    _cs_version=$(grep -m1 "^VERSION=" "$INSTALL_DIR/ags" 2>/dev/null | cut -d'"' -f2 || echo "")
    _os=$(uname -s | tr '[:upper:]' '[:lower:]')
    _arch=$(uname -m)
    [ "$_arch" = "x86_64" ] && _arch="amd64"
    _tui_base="ags-tui-${_os}-${_arch}"
    _tui_dst="$INSTALL_DIR/ags-tui"
    _tui_url="${RELEASES_URL}/v${_cs_version}/${_tui_base}"
    # Older pinned releases published only the cs-tui asset. It is still a
    # usable picker when installed under the canonical name; use the matching
    # legacy checksum/signature basename below.
    if [ -n "$_cs_version" ] && ! curl -fsSL --head "$_tui_url" >/dev/null 2>&1; then
        _tui_base="cs-tui-${_os}-${_arch}"
        _tui_url="${RELEASES_URL}/v${_cs_version}/${_tui_base}"
    fi
    if [ -n "$_cs_version" ] && curl -fsSL --head "$_tui_url" >/dev/null 2>&1 \
        && curl -fsSL "$_tui_url" -o "$_tui_dst"; then
        installed "ags-tui" "$_tui_dst"
        chmod +x "$_tui_dst"

        # Verify cs-tui checksum (hard gate). The rule is the one stated in
        # lib/20-update.sh's verify_checksum: a gate that cannot verify must not
        # pass. An unfetchable .sha256 and a digest that cannot be computed both
        # leave the binary unverified, so both remove it.
        _checksum_url="${RELEASES_URL}/v${_cs_version}/${_tui_base}.sha256"
        _verified=0
        _mismatch=0
        if curl -fsSL "$_checksum_url" -o "$_tui_dst.sha256" 2>/dev/null; then
            _expected=$(awk '{print $1}' "$_tui_dst.sha256")
            _actual=""
            # `|| _actual=""`: the script runs under `set -euo pipefail`, so a
            # digest tool that exits non-zero would otherwise abort the whole
            # install here — leaving both the unverified binary and its .sha256
            # behind — rather than falling through to the removal below.
            if command -v sha256sum >/dev/null 2>&1; then
                _actual=$(sha256sum "$_tui_dst" 2>/dev/null | awk '{print $1}') || _actual=""
            elif command -v shasum >/dev/null 2>&1; then
                _actual=$(shasum -a 256 "$_tui_dst" 2>/dev/null | awk '{print $1}') || _actual=""
            fi
            if [ -n "$_expected" ] && [ -n "$_actual" ]; then
                if [ "$_expected" = "$_actual" ]; then
                    _verified=1
                else
                    _mismatch=1
                fi
            fi
            rm -f "$_tui_dst.sha256"
        fi
        if [ "$_verified" != 1 ]; then
            rm -f "$_tui_dst"
            if [ "$_mismatch" = 1 ]; then
                warn "ags-tui checksum verification failed -- removed"
            else
                warn "ags-tui could not be verified (no checksum or no digest tool) -- removed"
            fi
        fi

        # Verify ags-tui signature (best-effort: minisign may not be installed)
        _sig_url="${RELEASES_URL}/v${_cs_version}/${_tui_base}.minisig"
        if curl -fsSL "$_sig_url" -o "$_tui_dst.minisig" 2>/dev/null; then
            _ms_bin=""
            if command -v minisign >/dev/null 2>&1; then
                _ms_bin=$(command -v minisign)
            elif [ -x "$HOME/.local/bin/minisign" ]; then
                _ms_bin="$HOME/.local/bin/minisign"
            fi
            # Nothing to verify once the checksum gate above removed the binary:
            # minisign fails on a path that is not there, which would report a
            # signature failure for a removal the gate has already explained,
            # and send the reader after release-key tampering that never was.
            if [ -n "$_ms_bin" ] && [ -f "$_tui_dst" ]; then
                if ! "$_ms_bin" -Vm "$_tui_dst" -P "$CS_SIGN_PUBKEY" -x "$_tui_dst.minisig" >/dev/null 2>&1; then
                    rm -f "$_tui_dst" "$_tui_dst.minisig"
                    warn "ags-tui signature verification failed -- removed"
                fi
            fi
            rm -f "$_tui_dst.minisig"
        fi
    else
        info "ags-tui not available for ${_os}-${_arch} — run 'ags' for help, or build from source: cd tui && cargo build --release"
    fi
fi
if [ -x "$INSTALL_DIR/ags-tui" ]; then
    ln -sfn ags-tui "$INSTALL_DIR/cs-tui"
fi

# Remove a stale opposite-platform TUI binary so a cross-platform reinstall can
# never leave cs-tui and cs-tui.exe side by side — which would let PATH lookup
# or the sibling probe select the wrong one and fail to launch. Keep only the
# name this platform installs.
rm -f "$INSTALL_DIR/ags-tui.exe" "$INSTALL_DIR/cs-tui.exe"

# Deploy every shipped skill into one engine's skills directory: each
# SKILL.md, then the support files listed in CS_SKILL_FILES. Claude and Codex
# get identical copies.
_deploy_skills() {
    local dest="$1" skill skill_file
    for skill in "${CS_SKILLS[@]}"; do
        mkdir -p "$dest/$skill"
        if [ "$INSTALL_METHOD" = "local" ]; then
            cp "$SCRIPT_DIR/skills/$skill/SKILL.md" "$dest/$skill/"
        elif command -v curl >/dev/null 2>&1; then
            curl -fsSL "$REPO_URL/skills/$skill/SKILL.md" -o "$dest/$skill/SKILL.md" || error "Failed to download $skill skill"
        elif command -v wget >/dev/null 2>&1; then
            wget -q "$REPO_URL/skills/$skill/SKILL.md" -O "$dest/$skill/SKILL.md" || error "Failed to download $skill skill"
        fi
    done
    for skill_file in "${CS_SKILL_FILES[@]}"; do
        mkdir -p "$dest/$(dirname "$skill_file")"
        if [ "$INSTALL_METHOD" = "local" ]; then
            cp -p "$SCRIPT_DIR/skills/$skill_file" "$dest/$skill_file"
            continue
        elif command -v curl >/dev/null 2>&1; then
            curl -fsSL "$REPO_URL/skills/$skill_file" -o "$dest/$skill_file" || error "Failed to download $skill_file"
        elif command -v wget >/dev/null 2>&1; then
            wget -q "$REPO_URL/skills/$skill_file" -O "$dest/$skill_file" || error "Failed to download $skill_file"
        fi
        # A download carries no mode; only the helper scripts run.
        case "$skill_file" in
            */scripts/*) chmod +x "$dest/$skill_file" ;;
        esac
    done
}

if _install_has_engine claude; then
# Install hooks
installed "${#CS_HOOKS[@]} hooks" "$HOOKS_DIR/"
mkdir -p "$HOOKS_DIR"

# Remove any retired hook files that earlier cs versions installed but no longer ship.
# Settings.json entries are stripped further below. Retired hooks may sit in
# HOOKS_DIR or, for installs that deployed hooks flat, its parent directory.
for retired in "${RETIRED_HOOKS[@]}"; do
    for dir in "$HOOKS_DIR" "$HOOKS_PARENT_DIR"; do
        if [ -f "$dir/$retired" ]; then
            rm "$dir/$retired"
            info "  Removed retired hook: $dir/$retired"
        fi
    done
done

# The subdirectory copy is canonical; remove parent-level copies left by
# installs that deployed hooks flat into ~/.claude/hooks/.
for hook in "${CS_HOOK_FILES[@]}"; do
    if [ -f "$HOOKS_PARENT_DIR/$hook" ]; then
        rm "$HOOKS_PARENT_DIR/$hook"
        info "  Removed $HOOKS_PARENT_DIR/$hook"
    fi
done

if [ "$INSTALL_METHOD" = "local" ]; then
    # Install from local clone
    for hook in "${CS_HOOK_FILES[@]}"; do
        cp "$HOOKS_SOURCE/$hook" "$HOOKS_DIR/"
    done
else
    # Download from GitHub
    if command -v curl >/dev/null 2>&1; then
        for hook in "${CS_HOOK_FILES[@]}"; do
            curl -fsSL "$REPO_URL/hooks/$hook" -o "$HOOKS_DIR/$hook" || error "Failed to download $hook"
        done
    elif command -v wget >/dev/null 2>&1; then
        for hook in "${CS_HOOK_FILES[@]}"; do
            wget -q "$REPO_URL/hooks/$hook" -O "$HOOKS_DIR/$hook" || error "Failed to download $hook"
        done
    fi
fi

chmod +x "$HOOKS_DIR"/*.sh


# cs ships no slash commands now: each became a skill of the same name. A
# command file left from an earlier install would answer the same /name as
# its skill, so drop the ones cs itself deployed and nothing else.
for retired in "${RETIRED_COMMANDS[@]}"; do
    if [ -f "$COMMANDS_DIR/$retired" ]; then
        rm "$COMMANDS_DIR/$retired"
        info "  Removed retired command: $COMMANDS_DIR/$retired (now a skill)"
    fi
done

# Install skills
SKILLS_DIR="$HOME/.claude/skills"
MODS_SOURCE="$SCRIPT_DIR/mods"
installed "skills" "$SKILLS_DIR/"

# Drop skill directories earlier cs versions installed but no longer ship. A
# skill left on disk keeps answering its slash command, so a rename is not
# complete until the old directory is gone.
for retired in "${RETIRED_SKILLS[@]}"; do
    if [ -d "$SKILLS_DIR/$retired" ]; then
        rm -rf "$SKILLS_DIR/$retired"
        info "  Removed retired skill: $SKILLS_DIR/$retired/"
    fi
done

_deploy_skills "$SKILLS_DIR"

# A symlink anywhere on a mod file's deploy path (an earlier opt-in had the
# person link the whole directory at the checkout) is replaced by a real
# directory or file: copying through the link would write into its target
# instead of deploying. Checks the mod directory, the file's directory and
# the file itself.
_mod_path_real() {
    local rel="$1" p
    for p in "${rel%%/*}" "$(dirname "$rel")" "$rel"; do
        if [ -L "$SKILLS_DIR/$p" ]; then
            rm "$SKILLS_DIR/$p"
            info "  Replaced symlink $SKILLS_DIR/$p with a deployed copy"
        fi
    done
}

for mod_file in "${CS_MOD_FILES[@]}"; do
    _mod_path_real "$mod_file"
    mkdir -p "$SKILLS_DIR/$(dirname "$mod_file")"
    if [ "$INSTALL_METHOD" = "local" ]; then
        cp -p "$MODS_SOURCE/$mod_file" "$SKILLS_DIR/$mod_file"
    elif command -v curl >/dev/null 2>&1; then
        curl -fsSL "$REPO_URL/mods/$mod_file" -o "$SKILLS_DIR/$mod_file" || error "Failed to download $mod_file"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$REPO_URL/mods/$mod_file" -O "$SKILLS_DIR/$mod_file" || error "Failed to download $mod_file"
    fi
done

fi

if _install_has_engine codex; then
# Codex reads the same skills from its own home, so each engine registers one
# payload natively. CODEX_HOME is where Codex itself looks (setup.sh points it
# at the profile). Mods stay with Claude: they are Claude Code function hooks.
CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
CODEX_SKILLS_DIR="$CODEX_DIR/skills"
installed "Codex skills" "$CODEX_SKILLS_DIR/"
# Codex keeps its login in this directory; a first install creates it private.
[ -d "$CODEX_DIR" ] || mkdir -m 700 -p "$CODEX_DIR"
_deploy_skills "$CODEX_SKILLS_DIR"

# One SessionStart hook: after /clear it rebinds the session to the new
# thread and loads an armed rotation handoff. Codex skips a hook nobody has
# trusted, so the registration writes its trust hash too.
if command -v jq >/dev/null 2>&1; then
    installed "Codex hook" "$CODEX_DIR/hooks.json"
    _codex_hooks_register "$CODEX_DIR" "$(_codex_hook_command "$INSTALL_DIR/ags")" \
        || warn "Could not register the Codex hook in $CODEX_DIR/hooks.json; rotation after /clear needs it"
else
    warn "jq not found - the Codex hook (rotation after /clear) was not registered."
fi
fi

# Install shell completions
COMPLETIONS_SOURCE="$SCRIPT_DIR/completions"
COMPLETION_SETUP_NEEDED=""

# Bash completion
installed "completions" "bash, zsh"
mkdir -p "$BASH_COMPLETION_DIR"

if [ "$INSTALL_METHOD" = "local" ]; then
    cp "$COMPLETIONS_SOURCE/ags.bash" "$BASH_COMPLETION_DIR/"
else
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$COMPLETION_BASH_URL" -o "$BASH_COMPLETION_DIR/ags.bash" || warn "Failed to download bash completion"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$COMPLETION_BASH_URL" -O "$BASH_COMPLETION_DIR/ags.bash" || warn "Failed to download bash completion"
    fi
fi
if [ -f "$BASH_COMPLETION_DIR/ags.bash" ]; then
    cp "$BASH_COMPLETION_DIR/ags.bash" "$BASH_COMPLETION_DIR/cs.bash"
fi

# Zsh completion
mkdir -p "$ZSH_COMPLETION_DIR"

if [ "$INSTALL_METHOD" = "local" ]; then
    cp "$COMPLETIONS_SOURCE/_ags" "$ZSH_COMPLETION_DIR/"
else
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$COMPLETION_ZSH_URL" -o "$ZSH_COMPLETION_DIR/_ags" || warn "Failed to download zsh completion"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$COMPLETION_ZSH_URL" -O "$ZSH_COMPLETION_DIR/_ags" || warn "Failed to download zsh completion"
    fi
fi
if [ -f "$ZSH_COMPLETION_DIR/_ags" ]; then
    cp "$ZSH_COMPLETION_DIR/_ags" "$ZSH_COMPLETION_DIR/_cs"
fi

if _install_has_engine claude; then
# Configure Claude Code settings
installed "hook config" "~/.claude/settings.json"

# Create or merge settings.json
mkdir -p "$(dirname "$CLAUDE_SETTINGS")"

if ! command -v jq >/dev/null 2>&1; then
    warn "jq not found - cannot configure hooks automatically."
    warn "See README for manual hook configuration."
else
    # Start with existing settings or empty object
    if [ -f "$CLAUDE_SETTINGS" ]; then
        SETTINGS=$(cat "$CLAUDE_SETTINGS")
        # An empty or invalid-JSON settings.json would make every jq stage below
        # silently produce nothing; back it up and start fresh instead.
        if [ -z "${SETTINGS//[[:space:]]/}" ] || ! printf '%s' "$SETTINGS" | jq -e . >/dev/null 2>&1; then
            cp "$CLAUDE_SETTINGS" "$CLAUDE_SETTINGS.cs-bak" 2>/dev/null || true
            warn "settings.json was empty or invalid JSON — backed up to settings.json.cs-bak and starting fresh"
            SETTINGS='{}'
        fi
    else
        SETTINGS='{}'
    fi

    # Tilde spelling of HOOKS_DIR (settings.json entries use ~ instead of $HOME)
    HOOKS_TILDE_DIR="~/.claude/hooks/cs"
    # Hook commands are registered with the tilde spelling so a settings.json
    # carried between machines keeps working. The profile launcher leaves HOME
    # as the user's own, so a tilde there would run the stable install's hooks
    # instead of the profile's; setup.sh asks for the absolute spelling.
    case "${CS_HOOK_PATHS:-tilde}" in
        tilde) HOOK_COMMAND_DIR="$HOOKS_TILDE_DIR" ;;
        absolute) HOOK_COMMAND_DIR="$HOOKS_DIR" ;;
        *) error "CS_HOOK_PATHS must be tilde or absolute" ;;
    esac

    # Strip retired hooks from any event in settings.json (event-agnostic since
    # we don't know which event the old version registered them under). Covers
    # both deployment layouts.
    for retired in "${RETIRED_HOOKS[@]}"; do
        SETTINGS=$(_strip_hook_registration "$SETTINGS" "$HOOKS_PARENT_DIR/$retired" "~/.claude/hooks/$retired")
        SETTINGS=$(_strip_hook_registration "$SETTINGS" "$HOOKS_DIR/$retired" "$HOOKS_TILDE_DIR/$retired")
    done

    # Strip parent-level registrations of current hooks (flat-layout installs);
    # _merge_cs_hook re-registers each one under HOOKS_DIR below.
    for hook in "${CS_HOOKS[@]}"; do
        SETTINGS=$(_strip_hook_registration "$SETTINGS" "$HOOKS_PARENT_DIR/$hook" "~/.claude/hooks/$hook")
    done

    # Drop events that emptied out entirely after the strips
    SETTINGS=$(echo "$SETTINGS" | jq '
        if .hooks then
            .hooks |= with_entries(select(.value | length > 0))
            | if .hooks == {} then del(.hooks) else . end
        else . end
    ')

    # Merge hooks: strip cs's command from any wrapper's nested .hooks array,
    # drop wrappers that emptied out, then append a fresh standalone wrapper
    # for cs's hook. This preserves non-cs entries that the user co-shipped
    # inside the same wrapper (eg. `~/bin/claude-status` alongside cs's
    # session-end.sh) — the prior shape dropped the entire wrapper whenever
    # it contained cs's command, taking sibling user hooks with it.
    #
    # Flat-shape entries (no `.hooks` field, command at top level) pass
    # through untouched because the `if .hooks then ... else . end` branch
    # skips them. The spec tests in tests/test_hooks.sh embed this same
    # filter shape via _install_merge_filter — keep them aligned.
    _merge_cs_hook() {
        local event="$1" file="$2" timeout="$3" matcher="${4:-}" async="${5:-}" rewake="${6:-}"
        local path="$HOOKS_DIR/$file" tilde="$HOOKS_TILDE_DIR/$file" registered="$HOOK_COMMAND_DIR/$file"
        local append
        # asyncRewake makes a hook's exit 2 wake the model with its stderr,
        # wrapped in a system-reminder under the rewakeMessage prefix. It
        # implies async, so it does not also need the async flag. Without it the
        # hook still runs and its output is discarded — the wake becomes a
        # five-second toast nobody reads.
        #
        # The labels are static in settings.json while the one FileChanged entry
        # now carries two wake kinds — cross-session mail and the /clear
        # rotation kick — so they name neither. The stderr reason says which it
        # is; a label claiming "mail" would tell the user the wrong story about
        # what started the turn, and was doing exactly that until it was caught
        # in a live rotation.
        append=$(jq -n --arg cmd "$registered" --argjson timeout "$timeout" \
            --arg matcher "$matcher" --arg async "$async" --arg rewake "$rewake" '
            (if $matcher != "" then {matcher: $matcher} else {} end)
            + {hooks: [
                {type: "command", command: $cmd, timeout: $timeout}
                + (if $async == "true" then {async: true} else {} end)
                + (if $rewake == "true" then {
                       asyncRewake: true,
                       rewakeMessage: "cs woke this session:",
                       rewakeSummary: "cs"
                   } else {} end)
              ]}
        ')
        SETTINGS=$(echo "$SETTINGS" | jq \
            --arg event "$event" \
            --arg path "$path" \
            --arg tilde "$tilde" \
            --argjson append "$append" '
            .hooks[$event] = (
                ((.hooks[$event] // []) | map(
                    if .hooks then
                        .hooks |= map(select(.command != $path and .command != $tilde))
                    else . end
                ) | map(select(.hooks == null or (.hooks | length > 0))))
                + [$append]
            )
        ')
    }

    # Registration table: event, file, timeout, [matcher], [async], [rewake]
    #
    # FileChanged carries no matcher on purpose: for that event the matcher both
    # seeds the watch path and supplies the dispatch query as the changed file's
    # BASENAME, so a matcher naming the maildir would watch it and then never
    # fire — and maildir filenames are unpredictable, so no basename matcher can
    # be written either. The watch path arrives instead as watchPaths from
    # session-start.sh, and the hook filters file_path to its own mailbox.
    #
    # CwdChanged is registered for one reason: a cwd change REPLACES the
    # session's dynamic watch list with what its CwdChanged hooks return, so
    # answering nothing loses the maildir watch for the rest of the session.
    # Registering FileChanged is itself what opens that path, so the mailbox has
    # to answer the event its own registration enables.
    _merge_cs_hook SessionStart       session-start.sh       30
    _merge_cs_hook PostToolUse        autosave-commits.sh    10 "Write|Edit" true
    _merge_cs_hook Stop               narrative-reminder.sh  10
    _merge_cs_hook SessionEnd         session-end.sh         30
    _merge_cs_hook SubagentStart      subagent-context.sh    10
    _merge_cs_hook PostToolUseFailure tool-failure-logger.sh 10 "" true
    _merge_cs_hook PermissionRequest  session-auto-approve.sh 5 "Write|Edit"
    _merge_cs_hook PreToolUse         bash-logger.sh          5 "Bash"
    _merge_cs_hook UserPromptSubmit   scope-prompt.sh        10
    _merge_cs_hook FileChanged        narrative-reminder.sh  10 "" "" true
    _merge_cs_hook CwdChanged         narrative-reminder.sh   5

    # Register ags-statusline as the Claude Code status line. A status line the
    # user already configured is never replaced silently: prompt when a
    # terminal is attached, otherwise keep it and print how to switch.
    _statusline_cmd="$INSTALL_DIR/ags-statusline"
    _current_statusline=$(echo "$SETTINGS" | jq -r '.statusLine.command // ""')
    # A "no" is remembered here so `ags -update` (which re-runs this installer)
    # stops asking on every release. `ags -statusline enable` clears it,
    # `ags -statusline disable` sets it (KEEP IN SYNC with lib/70-statusline.sh).
    _statusline_declined="${CS_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/cs}/statusline-declined"
    # A preference memo must never take the install down with it. Both writes
    # below run under errexit and `touch` ends the && list, so a failure — an
    # unwritable ~/.config/cs, which an earlier root-run install leaves behind —
    # aborted the run BEFORE settings.json was written: hooks copied but never
    # registered, no version stamp, no completion message. Report and continue.
    # The second message is used when the memo did not land, so the user is not
    # told they will stop being asked when they will.
    # Declining is permanent, so it gets its own line rather than a clause at
    # the end of the outcome. The default answer at the replace prompt is "no",
    # which means a user pressing enter to skip one release opts out for good —
    # a decision they should see stated, not skim past.
    _remember_statusline_decline() {  # outcome_line, undo_hint
        if mkdir -p "$(dirname "$_statusline_declined")" 2>/dev/null \
            && touch "$_statusline_declined" 2>/dev/null; then
            info "$1"
            info "You won't be asked again. $2"
        else
            warn "$1"
            warn "  (could not record the choice in $_statusline_declined, so ags -update will ask again)"
        fi
    }

    # Show what is being offered before asking for it. The payload is fixed and
    # the segments are pinned: the live ones read git state, unread mail and
    # rate limits from whatever session is running, which would put the user's
    # own branch name and inbox into an installer preview. Best-effort — a
    # sample that cannot render must not stop the install, so every failure
    # path here falls through to the question on its own.
    _preview_statusline() {
        command -v jq >/dev/null 2>&1 || return 0
        [ -x "$INSTALL_DIR/ags-statusline" ] || return 0
        local sample
        sample=$(jq -nc '{
            session_name: "my-session",
            context_window: {used_percentage: 34},
            model: {display_name: "Opus 5", id: "claude-opus-5"},
            effort: {level: "high"},
            rate_limits: {five_hour: {used_percentage: 41},
                          seven_day: {used_percentage: 72}}
        }' 2>/dev/null) || return 0
        # Draw it for the terminal it will appear in. The statusline falls back
        # to its dark palette whenever it can measure nothing, and a subprocess
        # inherits no way to measure — so a light terminal saw a dark bar, which
        # is precisely the thing a "what it looks like" sample must not get
        # wrong. install.sh still owns the tty and has just installed the binary
        # that can answer, so it asks; an unknown answer is left unset and the
        # statusline keeps its own fallback.
        # Only signals already in the environment. `ags -detect-theme` would be
        # the accurate answer, but it asks the terminal over OSC 11 and writes
        # that probe straight to /dev/tty — which no capture can intercept, so
        # the escape and its reply paint themselves across the installer's
        # output. A preview is not worth a garbled screen: read what the
        # terminal has already published, and when it has published nothing,
        # leave the statusline its own fallback.
        local _theme="${CS_TERM_THEME:-}"
        if [ -z "$_theme" ] && [ -n "${COLORFGBG:-}" ]; then
            case "${COLORFGBG##*;}" in
                7|9|1[0-5]) _theme="light" ;;
                0|[1-6]|8)  _theme="dark" ;;
            esac
        fi
        case "$_theme" in light|dark) ;; *) _theme="" ;; esac
        # Exported in a subshell rather than as a command prefix: an empty
        # ${_theme:+...} expansion would vanish and leave the binary running as
        # the prefix's own argument list, which renders nothing.
        local rendered
        rendered=$(
            export CS_STATUSLINE_SEGMENTS=logo,session,model,ctx,limits
            [ -z "$_theme" ] || export CS_TERM_THEME="$_theme"
            printf '%s' "$sample" | "$INSTALL_DIR/ags-statusline" 2>/dev/null
        ) || return 0
        [ -n "$rendered" ] || return 0
        # No indent: the statusline opens with a reset that eats leading spaces,
        # so an indented printf produced a bar flush against the margin while
        # every other line sat three spaces in.
        echo ""
        info "   This is what it looks like:"
        printf '%s\n' "$rendered"
        echo ""
    }

    # Each branch only decides consent; the registration itself happens once
    # below. "quiet" re-registers an existing ags-statusline or cs-statusline entry (refreshing
    # the path) without announcing it.
    _register_statusline=""
    case "$_current_statusline" in
        */ags-statusline|*/cs-statusline)
            _register_statusline=quiet
            ;;
        *)
            if [ -f "$_statusline_declined" ]; then
                info "Status line not registered (declined earlier). Enable any time with: ags -statusline enable"
            elif [ -z "$_current_statusline" ]; then
                # The status bar is user-visible UI: claim it only with consent.
                # Interactive installs ask (default yes); non-interactive installs
                # leave it off and say how to enable.
                if [ -t 0 ]; then
                    _preview_statusline
                    # read -p prints its argument verbatim, so an escape in it
                    # would show as literal characters. Emit the styled prompt
                    # with echo -e and read with no prompt of its own.
                    echo -en "Register ${BOLD}ags-statusline${NC} as the Claude Code status line? [Y/n] "
                    read -n 1 -r
                    echo ""
                    if [[ $REPLY =~ ^[Nn]$ ]]; then
                        _remember_statusline_decline \
                            "Status line not registered." \
                            "Turn it on any time with: ags -statusline enable"
                    else
                        _register_statusline=1
                    fi
                else
                    info "Status line not registered. Enable any time with: ags -statusline enable"
                fi
            else
                if [ -t 0 ]; then
                    _preview_statusline
                    echo -en "Replace current status line ($_current_statusline) with ${BOLD}ags-statusline${NC}? [y/N] "
                    read -n 1 -r
                    echo ""
                    # Anything but y declines, enter included: the point of the
                    # change is that ags -update stops asking, and a default that
                    # left the question open would re-prompt the people it was
                    # written for. The decline says plainly that it is
                    # remembered, and ags -statusline enable reverses it.
                    if [[ $REPLY =~ ^[Yy]$ ]]; then
                        _register_statusline=1
                    else
                        _remember_statusline_decline \
                            "Keeping current status line." \
                            "To switch to ags-statusline: ags -statusline enable"
                    fi
                else
                    warn "Keeping current status line. To switch to ags-statusline:"
                    warn "  set statusLine.command to $_statusline_cmd in ~/.claude/settings.json"
                fi
            fi
            ;;
    esac
    # The rounded capsule caps are the bar's one private-use glyph, so the
    # renderer draws square ends until this machine has said its font has
    # them. Ask once, here, while the sample is still on screen; the answer
    # is per machine and `ags -statusline caps on|off|ask` rewrites it (KEEP
    # THE PATH IN SYNC with lib/70-statusline.sh and bin/ags-statusline).
    # Non-interactive installs write nothing and say how to answer later.
    _statusline_caps="${XDG_CONFIG_HOME:-$HOME/.config}/cs/statusline-caps"
    if [ -n "$_register_statusline" ] && [ ! -f "$_statusline_caps" ]; then
        if [ -t 0 ]; then
            printf '\n  %s\n' "$(printf '\xee\x82\xb6')ags-statusline$(printf '\xee\x82\xb4')"
            # An explicit y or n only: the registration question just above
            # reads one key, so an Enter typed after it is still queued and
            # would answer this one. EOF (Ctrl-D) leaves the question
            # unanswered and lets the install finish; `read` returning
            # non-zero must not trip errexit before settings.json is written.
            _caps_answer=""
            while :; do
                echo -en "Do the ends of that capsule render as rounded shapes (not boxes)? [y/n] "
                if ! read -n 1 -r; then echo ""; break; fi
                echo ""
                case "$REPLY" in
                    [Yy]) _caps_answer=on; break ;;
                    [Nn]) _caps_answer=off; break ;;
                esac
            done
            if [ -z "$_caps_answer" ]; then
                info "Capsule caps: left unanswered (square ends). Answer later with: ags -statusline caps ask"
            elif mkdir -p "$(dirname "$_statusline_caps")" 2>/dev/null \
                && printf '%s\n' "$_caps_answer" > "$_statusline_caps" 2>/dev/null; then
                info "Capsule caps: $_caps_answer. Change later with: ags -statusline caps on|off|ask"
            else
                warn "Capsule caps: $_caps_answer, but the answer could not be recorded in $_statusline_caps"
                warn "  The bar shows square ends until: ags -statusline caps $_caps_answer"
            fi
        else
            info "Capsule caps: square ends until you answer once with: ags -statusline caps ask"
        fi
    fi
    if [ -n "$_register_statusline" ]; then
        # refreshInterval keeps the bar repainting once a second while idle;
        # the logo's attention pulse animates on that timer. Registers BOTH
        # settings keys, same as `ags -statusline enable` — the two recipes
        # must stay equivalent (KEEP IN SYNC with lib/70-statusline.sh).
        SETTINGS=$(echo "$SETTINGS" | jq --arg cmd "$_statusline_cmd" \
            --arg subcmd "$INSTALL_DIR/ags-subagent-statusline" \
            '.statusLine = {type: "command", command: $cmd, refreshInterval: 1}
             | .subagentStatusLine = {type: "command", command: $subcmd}')
        if [ "$_register_statusline" = "1" ]; then
            installed "status line" "ags-statusline + ags-subagent-statusline"
        fi
    fi

    echo "$SETTINGS" > "$CLAUDE_SETTINGS"
fi

fi

# Check if ~/.local/bin is in PATH
if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    echo ""
    warn "   WARNING: $INSTALL_DIR is not in your PATH"
    echo ""
    warn "   Add this line to your ~/.bashrc, ~/.zshrc, or equivalent:"
    warn "     export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo ""
fi

# Get version for completion message
CS_VERSION=$(grep -m1 "^VERSION=" "$INSTALL_DIR/ags" 2>/dev/null | cut -d'"' -f2 || echo "unknown")

# Stamp the deployed-hooks version so ags -doctor can flag installs whose
# deployed artifacts lag behind the running ags binary.
if _install_has_engine claude && [ "$CS_VERSION" != "unknown" ]; then
    echo "$CS_VERSION" > "$HOOKS_DIR/.version"
fi

# Union with prior installed adapters: deselection does not uninstall them.
# Updates must keep maintaining an adapter that remains deployed on disk.
_previous_engines=$(cat "$INSTALL_CONFIG" 2>/dev/null) || _previous_engines=""
case "$_previous_engines" in
    claude|codex|claude,codex|codex,claude)
        if [ "$_previous_engines" != "$INSTALL_ENGINES" ]; then
            INSTALL_ENGINES=claude,codex
        fi ;;
esac
mkdir -p "$(dirname "$INSTALL_CONFIG")"
printf '%s\n' "$INSTALL_ENGINES" > "$INSTALL_CONFIG"

echo ""
echo -e "   ${GREEN}✓${NC} ${ORANGE}Installation complete${NC} ${COMMENT}(${CS_VERSION})${NC}"
echo ""

# Check if completion setup is needed
SHELL_NAME=$(basename "$SHELL")
case "$SHELL_NAME" in
    bash)
        if ! grep -q 'bash_completion.d/ags.bash' "$HOME/.bashrc" 2>/dev/null; then
            warn "   To enable tab completion, add to ~/.bashrc:"
            warn "     [[ -f ~/.bash_completion.d/ags.bash ]] && source ~/.bash_completion.d/ags.bash"
            echo ""
        fi
        ;;
    zsh)
        if ! grep -qE 'fpath.*zsh/completions?' "$HOME/.zshrc" 2>/dev/null; then
            warn "   To enable tab completion, add to ~/.zshrc (before compinit):"
            warn "     fpath=(~/.zsh/completions \$fpath)"
            warn "     autoload -Uz compinit && compinit"
            echo ""
        fi
        ;;
esac

echo -e "   ${RUST}Usage:${NC} ags ${GOLD}<session-name>${NC}"
echo ""
echo -e "   ${COMMENT}Examples:${NC}"
echo -e "     ${COMMENT}ags${NC} ${GOLD}debug-api${NC}    ${COMMENT}# Create or resume session${NC}"
echo -e "     ${COMMENT}ags${NC} ${GOLD}server-fix${NC}   ${COMMENT}# Work on server issues${NC}"
echo ""

echo ""
echo "Getting started:"
echo "  ags my-first-session --engine ${INSTALL_ENGINES%%,*}    # Create your first session"
echo "  ags -help               # See all commands"
echo "  ags -version            # Verify installation"
echo "  cs remains available as a compatibility alias"
