# ABOUTME: Session .gitignore setup, adopting an existing project, and full uninstall.
# ABOUTME: Backs 'cs -adopt' and 'cs -uninstall'.

create_session_gitignore() {
    local session_dir="$1"
    cat > "$session_dir/.gitignore" << 'GITIGNORE'
# Transient files
*.lock
*.tmp
*.bak
.cs-tmp.*

# Per-actor local state (never shared)
.cs/local/

# Session archives (large binaries; unrelated to the tracked .cs/archived marker)
.cs/archives/

# An encrypted session's mounted volume (never staged in plaintext)
.cs/vault-mnt/

# Session cooldown markers
.cs/.narrative-reminder-cooldown

# Claude Code local settings (recreated by cs on each machine)
.claude/settings.local.json

# cs session protocol (machine-local; regenerated by cs on each machine)
CLAUDE.local.md

# OS files
.DS_Store
Thumbs.db

# Editor and tool config
.vscode/
.idea/
.obsidian/
*.swp
*.swo
*~
GITIGNORE
}

# Append cs's .gitignore entries to a session's .gitignore if absent
# (idempotent; never clobbers a project's existing .gitignore). Writes a fresh
# cs .gitignore when none exists. Used by adopt and by migrate_session so older
# sessions gain the .cs/local/ rule (per-actor state must never be committed).
ensure_cs_gitignore_entries() {
    local target_dir="$1"
    local gitignore="$target_dir/.gitignore"
    if [ ! -f "$gitignore" ]; then
        create_session_gitignore "$target_dir"
        return 0
    fi
    local entries
    entries=$(cat << 'ENTRIES'
.cs/local/
.cs/archives/
.cs/vault-mnt/
.cs/.narrative-reminder-cooldown
.claude/settings.local.json
CLAUDE.local.md
.obsidian/
.cs-tmp.*
ENTRIES
    )
    local line
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        [[ "$line" == \#* ]] && continue
        if ! grep -qF "$line" "$gitignore" 2>/dev/null; then
            echo "$line" >> "$gitignore"
        fi
    done <<< "$entries"
}

# Adopt an existing project directory as a cs session
adopt_session() {
    local session_name="$1"
    local target_dir
    target_dir="$(pwd -P)"

    validate_session_name "$session_name"

    # A linked git worktree keeps a `.git` FILE, so the init path below would
    # read it as "not a repo", `git init` over it and `git add -A` the user's
    # PR branch. Claude Code's worktrees have their own verb.
    if [ -f "$target_dir/.git" ]; then
        error "$target_dir is a linked git worktree. For Claude Code's worktrees run cs -adopt --worktrees from the repo; plain cs -adopt would commit into this branch."
    fi

    # A .cs/ directory with no session link is orphaned: `cs -rm`/the TUI's `d`
    # only ever remove the symlink, by design, so records survive a removal —
    # but re-adopting under the right name used to hit a flat "already a cs
    # session" refusal with no way back in short of hand-deleting .cs/. Tell
    # the two cases apart: a live link elsewhere names the session to resume
    # instead; an orphan gets offered a re-adopt that keeps its records.
    if [ -d "$target_dir/.cs" ]; then
        local existing_link existing_name=""
        for existing_link in "${SESSIONS_ROOT:-}"/*; do
            [ -L "$existing_link" ] || continue
            if [ "$(_resolve_symlink_dir "$existing_link")" = "$target_dir" ]; then
                existing_name="$(basename "$existing_link")"
                break
            fi
        done

        if [ -n "$existing_name" ]; then
            error "Directory is already adopted as session '$existing_name' (open it with: cs $existing_name)"
        fi

        if cs_interactive; then
            local confirm
            read -r -p "Found existing session records (.cs/) with no session link. Re-adopt as '$session_name', preserving them? [y/N] " confirm
            if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
                info "Cancelled"
                return 0
            fi
        else
            error "Directory carries session records (.cs/) but no session link. Re-run interactively to re-adopt them as '$session_name', or remove .cs/ to adopt fresh."
        fi
    fi

    # Check if session name is taken
    local session_link="$SESSIONS_ROOT/$session_name"
    if [ -e "$session_link" ] || [ -L "$session_link" ]; then
        error "Session '$session_name' already exists"
    fi

    # create_session_structure writes CLAUDE.local.md, never CLAUDE.md — a
    # project's own CLAUDE.md is left untouched.
    #
    # It also stages a conversation id and a colour for a brand-new session's
    # first launch. An adopted directory already exists, so its first open is
    # a reopen: a first adoption keeps no id (the launch records one when it
    # starts the first conversation), and re-adopted records keep the
    # conversation and the colour they name. Only a UUID names a conversation
    # and only one of claude's colours is a colour; anything else is dropped,
    # and said.
    local prior_binding prior_color
    prior_binding=$(_read_local_state "$target_dir/.cs/local/state" claude_session_id)
    prior_color=$(_read_local_state "$target_dir/.cs/local/state" claude_session_color)
    create_session_structure "$target_dir"
    if _is_uuid "$prior_binding"; then
        _set_local_state "$target_dir/.cs/local/state" claude_session_id "$prior_binding"
    else
        [ -z "$prior_binding" ] || warn "ignoring claude_session_id in .cs/local/state: not a UUID, so it names no conversation"
        _unset_local_state "$target_dir/.cs/local/state" claude_session_id
    fi
    if _is_session_color "$prior_color"; then
        _set_local_state "$target_dir/.cs/local/state" claude_session_color "$prior_color"
    elif [ -n "$prior_color" ]; then
        warn "ignoring claude_session_color in .cs/local/state: not one of claude's colours"
    fi

    # An adopted session's name is the link's, not the directory's, and the link
    # is the only place it lives — so a hook that resolves this project by
    # walking up from it has nothing to read. Record it where that walk looks
    # (hooks/cs-resolve.sh's _cs_session_name).
    _set_local_state "$target_dir/.cs/local/state" session_name "$session_name"

    # A project Claude Code already ran in has said what it is about: its
    # newest conversation's first prompt becomes the Objective, the line the
    # picker previews and searches. The prompt hook does the same for a live
    # session, so a project with no conversation keeps the placeholder for
    # the first prompt typed after the open.
    local adopt_proj adopt_uuid adopt_objective
    adopt_proj=$(_claude_project_dir "$target_dir")
    adopt_uuid=$(_discover_session_uuid_in "$adopt_proj")
    if [ -n "$adopt_uuid" ]; then
        adopt_objective=$(_transcript_first_prompt "$adopt_proj/$adopt_uuid.jsonl")
        _seed_readme_objective "$target_dir/.cs/README.md" "$adopt_objective"
    fi

    # Create symlink from sessions root
    mkdir -p "$SESSIONS_ROOT"
    ln -s "$target_dir" "$session_link"

    # Initialize git if not already a repo
    if [ ! -d "$target_dir/.git" ]; then
        (
            cd "$target_dir" || exit 0
            create_session_gitignore "$target_dir"
            git init -q 2>/dev/null || true
            # See the session-init path: autocrlf would rewrite .gitignore to
            # CRLF and its patterns would stop matching.
            git config core.autocrlf false 2>/dev/null || true
            git branch -M main 2>/dev/null || true
            setup_merge_attributes "$target_dir"
            git add -A 2>/dev/null || true
            git commit -q -m "Adopt as cs session: $session_name" 2>/dev/null || true
        )
    else
        # Merge cs's .gitignore entries into the project's existing .gitignore
        ensure_cs_gitignore_entries "$target_dir"

        # Commit the adoption
        (
            cd "$target_dir" || exit 0
            setup_merge_attributes "$target_dir"
            git add .cs/ .gitignore .gitattributes 2>/dev/null || true
            # The commit names its own paths: this runs inside the user's
            # project repo, and a bare `git commit` would sweep whatever they
            # had staged into a commit titled "Adopt as cs session". The
            # --cached check is scoped the same way, or a user's unrelated
            # staged file would make cs commit when it has nothing to say.
            # (`git commit -- <paths>` only matches TRACKED paths, so the add
            # above is what makes the new .cs files eligible.)
            if ! git diff --cached --quiet -- .cs/ .gitignore .gitattributes 2>/dev/null; then
                git commit -q -m "Adopt as cs session: $session_name" -- .cs/ .gitignore .gitattributes 2>/dev/null || true
            fi
        )
    fi

    info "Adopted $(basename "$target_dir") as session '$session_name'"
    echo -e "${DIM}Symlink: $session_link -> $target_dir${NC}"
    echo -e "${DIM}Resume with: cs $session_name${NC}"
}

# Append each entry to a git exclude file once. Append only: the file may hold
# the user's own rules, and a linked worktree reads only the common one.
_append_exclude_once() {  # exclude_file, entry...
    local file="$1"; shift
    mkdir -p "$(dirname "$file")"
    [ -f "$file" ] || : > "$file"
    # A last line with no newline would swallow the first entry appended to it.
    if [ -s "$file" ] && [ -n "$(tail -c 1 "$file")" ]; then
        printf '\n' >> "$file"
    fi
    local entry
    for entry in "$@"; do
        grep -qxF -- "$entry" "$file" || printf '%s\n' "$entry" >> "$file"
    done
}

# The .cs/ skeleton for a Claude Code worktree adopted as a session. Not
# create_session_structure: that commits into the checkout, and the checkout
# is a live PR branch. Not bootstrap_worktree_meta: its README names a base
# session and a cs/<task> branch, which an adopted worktree has neither of.
_bootstrap_adopted_worktree_meta() {  # wt_dir, session_name
    local wt_dir="$1" session_name="$2"
    mkdir -p "$wt_dir/.cs/memory"
    _write_session_readme_head "$wt_dir/.cs/README.md" "$session_name" "[]" "[\"$session_name\"]"
    cat >> "$wt_dir/.cs/README.md" << EOF
Claude Code worktree \`$(basename "$wt_dir")\`, adopted from $wt_dir.

## Objective

[Describe what you're trying to accomplish in this session]

## Outcome

[To be filled when session is complete - summarize what was accomplished]
EOF
    cat > "$wt_dir/.cs/local/session.log" << EOF
Claude Code Session Log
Session: $session_name
Started: $(date '+%Y-%m-%d %H:%M:%S')

================================================================================

EOF
    ensure_narrative_file "$wt_dir"
}

# Register every worktree Claude Code created under <repo>/.claude/worktrees/
# as a session named <repo>.<worktree>, bound to the conversation it already
# holds. One worktree is one conversation, which is cs's own model, so nothing
# changes shape: the session link points into the repo, the state binds the
# UUID, and the Objective is the conversation's first prompt. The checkout is
# a live PR branch, so cs's files are hidden through the repo's common exclude
# rather than committed, and the tracked CLAUDE.md is never touched.
#
# `.` separates repo and worktree because `@` already means <base>@<task> and
# would make cs look for a base session. No cs_base is recorded: these are
# peers, and a base would fuse their task lists and keychain namespaces.
#
# A re-run adopts what is new, skips what is already a session, finishes an
# adoption that stopped before its link was made, and prunes the links it made
# for worktrees Claude Code has since deleted.
adopt_worktrees() {  # [--dry-run]
    local dry_run=0 arg
    for arg in "$@"; do
        case "$arg" in
            --dry-run) dry_run=1 ;;
            *) error "Unknown option for cs -adopt --worktrees: $arg (only --dry-run)" ;;
        esac
    done

    local repo
    repo=$(git rev-parse --show-toplevel 2>/dev/null) \
        || error "cs -adopt --worktrees reads <repo>/.claude/worktrees, and $(pwd) is not inside a git repository"
    repo=$(cd "$repo" && pwd -P)
    local wt_root="$repo/.claude/worktrees"
    [ -d "$wt_root" ] || error "No Claude Code worktrees to adopt: $wt_root does not exist"
    local repo_name common
    repo_name=$(basename "$repo")
    common=$(git -C "$repo" rev-parse --git-common-dir)
    case "$common" in /*) ;; *) common="$repo/$common" ;; esac

    # Prune links this command made for worktrees that no longer exist.
    local link target
    for link in "$SESSIONS_ROOT/$repo_name".*; do
        [ -L "$link" ] || continue
        target=$(readlink "$link")
        case "$target" in "$wt_root"/*) ;; *) continue ;; esac
        [ -d "$target" ] && continue
        if [ "$dry_run" = 1 ]; then
            echo "would prune $(basename "$link"): $target is gone"
        else
            rm "$link"
            info "Pruned $(basename "$link"): $target is gone"
        fi
    done

    local wt_dir wt_name session_name proj parent_proj uuid adopted=0 wt_top wt_common state tracked
    for wt_dir in "$wt_root"/*/; do
        wt_dir="${wt_dir%/}"
        [ -d "$wt_dir" ] || continue
        wt_name=$(basename "$wt_dir")
        session_name="$repo_name.$wt_name"
        link="$SESSIONS_ROOT/$session_name"
        # Everything below writes into this directory, so it has to be a
        # checkout of this repo: its own worktree root, on this repo's common
        # git dir. A symlink to another project, or a plain folder, is neither.
        wt_top=$(git -C "$wt_dir" rev-parse --show-toplevel 2>/dev/null) || wt_top=""
        wt_common=$(cd "$wt_dir" && cd "$(git rev-parse --git-common-dir 2>/dev/null)" 2>/dev/null && pwd -P) || wt_common=""
        if [ -L "$wt_dir" ] || [ -z "$wt_top" ] || ! [ "$wt_top" -ef "$wt_dir" ] || ! [ "$wt_common" -ef "$common" ]; then
            echo -e "${DIM}skip $wt_name: not a worktree of $repo${NC}"
            continue
        fi
        state="$wt_dir/.cs/local/state"
        if [ -d "$wt_dir/.cs" ]; then
            # Three kinds of .cs/ can sit here. One this command marked and
            # linked is a session, or was one until `cs -rm` took the link
            # and left .cs/ behind as that verb does; neither is re-adopted,
            # the second is named so the user knows how to get it back. One it
            # marked and never linked died part-way and is finished below.
            # Anything else is someone's session.
            if [ "$(_read_local_state "$state" git_bookkeeping)" != "exclude" ] || [ -e "$link" ] || [ -L "$link" ]; then
                # A run that died between ln -s and the marker left a linked
                # session without one; without it a later cs -rm would be undone.
                if [ "$(_read_local_state "$state" git_bookkeeping)" = "exclude" ] && [ -z "$(_read_local_state "$state" adopted)" ] \
                    && [ -L "$link" ] && [ "$(readlink "$link")" = "$wt_dir" ] && [ "$dry_run" != 1 ]; then
                    _set_local_state "$state" adopted "$(date '+%Y-%m-%d')"
                fi
                echo -e "${DIM}skip $wt_name: already carries .cs/${NC}"
                continue
            fi
            if [ -n "$(_read_local_state "$state" adopted)" ]; then
                echo -e "${DIM}skip $wt_name: removed with cs -rm (delete its .cs/ to adopt it again)${NC}"
                continue
            fi
        fi
        # A running worktree session writes under the worktree's own project
        # dir; one that has exited was moved into the parent repo's. Look in
        # both, and keep proj naming the dir the transcript was found in: the
        # Objective is read from it below.
        proj=$(_claude_project_dir "$wt_dir")
        uuid=$(_discover_session_uuid_in "$proj")
        if [ -z "$uuid" ]; then
            parent_proj=$(_claude_project_dir "$repo")
            uuid=$(_discover_worktree_uuid_in "$parent_proj" "$wt_dir")
            if [ -z "$uuid" ]; then
                echo -e "${DIM}skip $wt_name: no conversation under $proj, none relocated into $parent_proj${NC}"
                continue
            fi
            proj="$parent_proj"
        fi
        # The open refuses the same conflict; skipping here keeps a worktree
        # from being registered as a session that can never open.
        tracked=$(_exclude_session_tracked_conflict "$wt_dir")
        if [ -n "$tracked" ]; then
            case "$tracked" in
                *symlink) echo -e "${DIM}skip $wt_name: $tracked, and cs writes through it at every open${NC}" ;;
                *) echo -e "${DIM}skip $wt_name: $tracked is tracked on its branch, and cs would rewrite it at every open${NC}" ;;
            esac
            continue
        fi
        validate_session_name "$session_name"
        if [ -e "$link" ] || [ -L "$link" ]; then
            error "Session '$session_name' already exists: the same repo name in two places? ($(readlink "$link" 2>/dev/null || echo "$link"))"
        fi
        if [ "$dry_run" = 1 ]; then
            echo "would adopt $wt_name as '$session_name' (conversation $uuid)"
            continue
        fi
        # Hidden before anything exists to hide, marked before anything else
        # is written: a run that dies part-way leaves nothing git can see and
        # a .cs/ the next run knows to finish.
        _append_exclude_once "$common/info/exclude" ".cs/" ".claude/settings.local.json" "CLAUDE.local.md"
        mkdir -p "$wt_dir/.cs/local"
        # The open reads this and keeps its hands off the tracked tree: no
        # .gitignore or .gitattributes backfill, no CLAUDE.md migration (see
        # migrate_session).
        _set_local_state "$state" git_bookkeeping exclude
        [ -f "$wt_dir/.cs/README.md" ] || _bootstrap_adopted_worktree_meta "$wt_dir" "$session_name"
        _set_local_state "$state" claude_session_id "$uuid"
        _set_local_state "$state" session_name "$session_name"
        _seed_readme_objective "$wt_dir/.cs/README.md" "$(_transcript_first_prompt "$proj/$uuid.jsonl")"
        mkdir -p "$SESSIONS_ROOT"
        ln -s "$wt_dir" "$link"
        # Written last: its absence is what tells a half-done adoption apart
        # from a session cs -rm removed.
        _set_local_state "$state" adopted "$(date '+%Y-%m-%d')"
        adopted=$((adopted + 1))
        info "Adopted $wt_name as session '$session_name'"
    done
    [ "$dry_run" = 1 ] || echo -e "${DIM}$adopted adopted; open one with: cs $repo_name.<worktree>${NC}"
}

# Take back the Ctrl+X R / Ctrl+X W bindings the installer added, and the
# Option+1 / Option+2 ones an earlier cs added, only where a key still holds
# cs's value: a key bound to anything else is the user's. A Global block left
# empty by that goes, and so does a file left as exactly {"bindings":[]},
# unless it is a symlink, whose target is written through instead so a
# dotfiles manager's copy does not keep cs's keys. The recorded answer goes
# too, so a later install asks again.
_uninstall_rotate_wrap_keys() {
    local file ours held stripped
    file="$(_cs_keybindings_file)"
    rm -f "$(_cs_rotate_wrap_keys_answer_file)"
    [ -e "$file" ] || return 0
    if ! command -v jq >/dev/null 2>&1; then
        warn "jq not found - cannot remove cs's rotate/wrap bindings from $file"
        return 0
    fi
    if ! _cs_keybindings_shape_ok "$file"; then
        warn "Left $file as it is: not JSON with a \"bindings\" array"
        return 0
    fi
    ours=$(jq -cn --argjson a "$CS_ROTATE_WRAP_KEYS" --argjson b "$CS_RETIRED_OPTION_KEYS" '$a + $b')
    held=$(_cs_keybindings_held "$ours" < "$file") || {
        warn "Could not read $file; its rotate/wrap bindings were left in place"
        return 0
    }
    [ -n "$held" ] || return 0
    stripped=$(_cs_keybindings_strip "$ours" < "$file") || {
        warn "Could not read $file; its rotate/wrap bindings were left in place"
        return 0
    }
    if [ "$stripped" = '{"bindings":[]}' ] && [ ! -L "$file" ]; then
        rm -f "$file"
        info "Removed $file"
    elif cs_write_atomic "$file" jq . <<< "$stripped"; then
        info "Removed cs's $held bindings from $file"
    else
        warn "Could not write $file; its rotate/wrap bindings were left in place"
    fi
}

# Uninstall cs and all components
run_uninstall() {
    local install_dir="$HOME/.local/bin"
    local hooks_parent_dir="$HOME/.claude/hooks"
    local hooks_dir="$hooks_parent_dir/cs"
    local commands_dir="$HOME/.claude/commands"
    local skills_dir="$HOME/.claude/skills"
    local settings_file="${CS_CLAUDE_DIR:-$HOME/.claude}/settings.json"
    local bash_completion_dir="$HOME/.bash_completion.d"
    # install.sh picks the zsh completion dir from the user's fpath line: its
    # default ~/.zsh/completions, or ~/.zsh/completion when .zshrc spells it
    # singular. install.sh runs as a lone downloaded file with no lib/ on disk,
    # so that detection cannot be shared as code. Rather than mirroring its
    # regex here, sweep BOTH spellings: `~/\.zsh/completions?` can only ever
    # yield those two, so a superset cannot drift with the detection — and it
    # still finds the file when .zshrc was edited after the install.
    # KEEP IN SYNC with install.sh's ZSH_COMPLETION_DIR block: a third candidate
    # there needs an entry here.
    local zsh_completion_dirs=("$HOME/.zsh/completions" "$HOME/.zsh/completion")
    # check_update_notify stamps update-check and update-notes-* here; they
    # outlived a full uninstall and made the next install look up to date.
    local update_cache_dir="$HOME/.cache/cs"

    warn "This will uninstall cs and all its components:"
    echo "  - $install_dir/cs, $install_dir/cs-secrets, $install_dir/cs-statusline, $install_dir/cs-subagent-statusline, $install_dir/cs-tui(.exe)"
    echo "  - Hooks in $hooks_dir/"
    echo "  - Commands in $commands_dir/"
    echo "  - Skills in $skills_dir/"
    echo "  - Shell completions"
    echo "  - Update-check cache in $update_cache_dir/"
    echo "  - Hook entries in $settings_file"
    echo "  - cs's rotate/wrap key bindings in $(_cs_keybindings_file)"
    echo ""
    read -p "Continue with uninstall? [y/N] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        info "Uninstall cancelled."
        return 0
    fi

    echo ""
    info "Uninstalling cs..."
    echo ""

    # Remove binaries
    if [ -f "$install_dir/cs" ]; then
        rm "$install_dir/cs"
        info "Removed $install_dir/cs"
    fi

    if [ -f "$install_dir/cs-secrets" ]; then
        rm "$install_dir/cs-secrets"
        info "Removed $install_dir/cs-secrets"
    fi

    if [ -f "$install_dir/cs-statusline" ]; then
        rm "$install_dir/cs-statusline"
        info "Removed $install_dir/cs-statusline"
    fi

    if [ -f "$install_dir/cs-subagent-statusline" ]; then
        rm "$install_dir/cs-subagent-statusline"
        info "Removed $install_dir/cs-subagent-statusline"
    fi

    # Remove the statusLine registration only when it points at cs-statusline;
    # a status line the user configured themselves is left untouched.
    if command -v jq >/dev/null 2>&1 && _strip_statusline_registration "$settings_file"; then
        info "Removed cs-statusline registration from settings.json"
    fi

    # Remove the subagentStatusLine registration only when it points at
    # cs-subagent-statusline; a row renderer the user configured is left alone.
    if command -v jq >/dev/null 2>&1 && _strip_subagent_statusline_registration "$settings_file"; then
        info "Removed cs-subagent-statusline registration from settings.json"
    fi

    rm -f "$(_statusline_declined_marker)"

    # The .exe name is only ever a leftover from an install that predates
    # dropping Windows; remove it too so an upgrade leaves nothing behind.
    for _tui in cs-tui cs-tui.exe; do
        if [ -f "$install_dir/$_tui" ]; then
            rm "$install_dir/$_tui"
            info "Removed $install_dir/$_tui"
        fi
    done

    # Remove hooks from both deployment layouts (subdirectory and flat)
    local hook dir
    for hook in "${CS_HOOKS[@]}" "${CS_HOOK_LIBS[@]}"; do
        for dir in "$hooks_dir" "$hooks_parent_dir"; do
            if [ -f "$dir/$hook" ]; then
                rm "$dir/$hook"
                info "Removed $dir/$hook"
            fi
        done
    done

    # Remove retired hook files left behind from older cs versions
    local retired
    for retired in "${RETIRED_HOOKS[@]}"; do
        for dir in "$hooks_dir" "$hooks_parent_dir"; do
            if [ -f "$dir/$retired" ]; then
                rm "$dir/$retired"
                info "Removed retired $dir/$retired"
            fi
        done
    done
    rm -f "$hooks_dir/.version"
    rmdir "$hooks_dir" 2>/dev/null || true

    # Remove commands
    for cmd in "${CS_COMMANDS[@]}"; do
        if [ -f "$commands_dir/$cmd" ]; then
            rm "$commands_dir/$cmd"
            info "Removed $commands_dir/$cmd"
        fi
    done

    # Remove skills, current and retired. A machine that never ran an install
    # carrying the rename still has the old directory, so uninstall must clear
    # both lists or it leaves cs files behind.
    local skill
    for skill in "${CS_SKILLS[@]}" "${RETIRED_SKILLS[@]}"; do
        if [ -d "$skills_dir/$skill" ]; then
            rm -rf "$skills_dir/$skill"
            info "Removed $skills_dir/$skill/"
        fi
    done

    # Remove mods: each deploys under its own directory beside the skills.
    # Ownership is by name, as for the skills above: cs deploys these names
    # and removes them whole, extra files included. Do not re-fix.
    local mod_file mod
    for mod_file in "${CS_MOD_FILES[@]}"; do
        mod="${mod_file%%/*}"
        if [ -d "$skills_dir/$mod" ]; then
            rm -rf "$skills_dir/$mod"
            info "Removed $skills_dir/$mod/"
        fi
    done

    # Remove shell completions
    if [ -f "$bash_completion_dir/cs.bash" ]; then
        rm "$bash_completion_dir/cs.bash"
        info "Removed $bash_completion_dir/cs.bash"
    fi

    local zsh_dir
    for zsh_dir in "${zsh_completion_dirs[@]}"; do
        if [ -f "$zsh_dir/_cs" ]; then
            rm "$zsh_dir/_cs"
            info "Removed $zsh_dir/_cs"
        fi
    done

    if [ -d "$update_cache_dir" ]; then
        rm -rf "$update_cache_dir"
        info "Removed $update_cache_dir"
    fi

    # The launch's hard links named claude, one whole binary per version.
    local claude_links_dir="$HOME/.local/share/cs/claude"
    if [ -d "$claude_links_dir" ]; then
        rm -rf "$claude_links_dir"
        info "Removed $claude_links_dir"
    fi

    # Clean up settings.json (remove cs hooks, preserve others)
    if [ -f "$settings_file" ] && command -v jq >/dev/null 2>&1; then
        local settings
        settings=$(cat "$settings_file")

        # Strip every cs hook (current and retired) from any event,
        # event-agnostic, matching both path spellings ($HOME and ~) in both
        # deployment layouts (subdirectory and flat). Drops wrappers that
        # empty out; sibling user hooks co-shipped in a wrapper survive.
        local strip_name
        for strip_name in "${CS_HOOKS[@]}" "${RETIRED_HOOKS[@]}"; do
            settings=$(_strip_hook_registration "$settings" "$hooks_dir/$strip_name" "~/.claude/hooks/cs/$strip_name")
            settings=$(_strip_hook_registration "$settings" "$hooks_parent_dir/$strip_name" "~/.claude/hooks/$strip_name")
        done

        # Clean up empty hook arrays
        settings=$(echo "$settings" | jq '
            if .hooks then
                .hooks |= with_entries(select(.value | length > 0))
                | if .hooks == {} then del(.hooks) else . end
            else . end
        ')

        echo "$settings" > "$settings_file"
        info "Cleaned up $settings_file"
    elif [ -f "$settings_file" ]; then
        warn "jq not found - cannot clean up $settings_file automatically"
        warn "Manually remove cs hook entries from $settings_file"
    fi

    _uninstall_rotate_wrap_keys

    # Ask about secrets in keychain
    if [ -d "$SESSIONS_ROOT" ]; then
        local sessions
        sessions=$(ls -1 "$SESSIONS_ROOT" 2>/dev/null || true)

        if [ -n "$sessions" ]; then
            echo ""
            warn "Secrets may exist in OS keychain for these sessions:"
            echo "$sessions" | while read -r s; do
                echo "  - $s"
            done
            echo ""
            read -p "Delete secrets from keychain? [y/N] " -n 1 -r
            echo ""
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                # Find cs-secrets script
                local secrets_script=""
                for loc in "$install_dir/cs-secrets" "/usr/local/bin/cs-secrets"; do
                    if [ -x "$loc" ]; then
                        secrets_script="$loc"
                        break
                    fi
                done

                if [ -n "$secrets_script" ]; then
                    echo "$sessions" | while read -r s; do
                        "$secrets_script" --session "$s" purge 2>/dev/null || true
                    done
                else
                    warn "cs-secrets not found - cannot purge secrets automatically"
                fi
            else
                info "Kept secrets in keychain"
            fi
        fi
    fi

    # Ask about session data. rm -rf recurses into a mount, so with a volume
    # mounted inside the sessions root (an open encrypted session's vault) the
    # data stays and the question is not asked.
    if [ -d "$SESSIONS_ROOT" ]; then
        echo ""
        local mounted
        if ! mounted=$(_volume_mounted_under "$SESSIONS_ROOT"); then
            warn "Kept $SESSIONS_ROOT: cs could not read the mount table, so it cannot tell whether a volume is mounted inside it."
        elif [ -n "$mounted" ]; then
            warn "Kept $SESSIONS_ROOT: a volume is mounted inside it at $mounted, and deleting the directory would delete what the volume holds. Unmount it before you delete $SESSIONS_ROOT."
        else
            warn "Session data exists at $SESSIONS_ROOT"
            read -p "Delete session data? This cannot be undone. [y/N] " -n 1 -r
            echo ""
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                rm -rf "$SESSIONS_ROOT"
                info "Removed $SESSIONS_ROOT"
            else
                info "Kept $SESSIONS_ROOT"
            fi
        fi
    fi

    echo ""
    info "Uninstall complete!"
}

# Main function
