# ABOUTME: Session .gitignore setup, adopting an existing project, and full uninstall.
# ABOUTME: Backs 'ags -adopt' and 'ags -uninstall'.

create_session_gitignore() {
    local session_dir="$1"
    cat > "$session_dir/.gitignore" << 'GITIGNORE'
# Transient files
*.lock
*.tmp
*.bak

# Per-actor local state (never shared)
.cs/local/

# Session archives (large binaries; unrelated to the tracked .cs/archived marker)
.cs/archives/

# Session cooldown markers
.cs/.narrative-reminder-cooldown

# Claude Code local settings (recreated by cs on each machine)
.claude/settings.local.json

# cs session protocol (machine-local; regenerated by cs on each machine)
CLAUDE.local.md

# OS files
.DS_Store
Thumbs.db

# Editor and tool config
.vscode/
.idea/
.obsidian/
*.swp
*.swo
*~
GITIGNORE
}

# Append cs's .gitignore entries to a session's .gitignore if absent
# (idempotent; never clobbers a project's existing .gitignore). Writes a fresh
# cs .gitignore when none exists. Used by adopt and by migrate_session so older
# sessions gain the .cs/local/ rule (per-actor state must never be committed).
ensure_cs_gitignore_entries() {
    local target_dir="$1"
    local gitignore="$target_dir/.gitignore"
    if [ ! -f "$gitignore" ]; then
        create_session_gitignore "$target_dir"
        return 0
    fi
    local entries
    entries=$(cat << 'ENTRIES'
.cs/local/
.cs/archives/
.cs/.narrative-reminder-cooldown
.claude/settings.local.json
CLAUDE.local.md
.obsidian/
ENTRIES
    )
    local line
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        [[ "$line" == \#* ]] && continue
        if ! grep -qF "$line" "$gitignore" 2>/dev/null; then
            echo "$line" >> "$gitignore"
        fi
    done <<< "$entries"
}

# Adopt an existing project directory as an agent-sessions workspace
adopt_session() {
    local session_name="${1:-}" explicit_engine="" engine
    [ "$#" -eq 0 ] || shift
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --engine)
                [ -n "${2:-}" ] || error "--engine needs claude or codex"
                explicit_engine="$2"; shift 2 ;;
            --engine=*) explicit_engine="${1#*=}"; shift ;;
            *) error "Usage: ags -adopt <name> [--engine claude|codex]" ;;
        esac
        cs_engine_known "$explicit_engine" || error "--engine needs claude or codex"
    done
    local target_dir
    target_dir="$(pwd -P)"

    validate_session_name "$session_name"
    engine=$(_session_engine "$target_dir" "$explicit_engine")

    # A .cs/ directory with no session link is orphaned: `cs -rm`/the TUI's `d`
    # only ever remove the symlink, by design, so records survive a removal —
    # but re-adopting under the right name used to hit a flat "already a cs
    # session" refusal with no way back in short of hand-deleting .cs/. Tell
    # the two cases apart: a live link elsewhere names the session to resume
    # instead; an orphan gets offered a re-adopt that keeps its records.
    if [ -d "$target_dir/.cs" ]; then
        local existing_link existing_name=""
        for existing_link in "${SESSIONS_ROOT:-}"/*; do
            [ -L "$existing_link" ] || continue
            if [ "$(_resolve_symlink_dir "$existing_link")" = "$target_dir" ]; then
                existing_name="$(basename "$existing_link")"
                break
            fi
        done

        if [ -n "$existing_name" ]; then
            error "Directory is already adopted as session '$existing_name' (open it with: ags $existing_name)"
        fi

        if cs_interactive; then
            local confirm
            read -r -p "Found existing session records (.cs/) with no session link. Re-adopt as '$session_name', preserving them? [y/N] " confirm
            if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
                info "Cancelled"
                return 0
            fi
        else
            error "Directory carries session records (.cs/) but no session link. Re-run interactively to re-adopt them as '$session_name', or remove .cs/ to adopt fresh."
        fi
    fi

    # Check if session name is taken
    local session_link="$SESSIONS_ROOT/$session_name"
    if [ -e "$session_link" ] || [ -L "$session_link" ]; then
        error "Session '$session_name' already exists"
    fi

    # create_session_structure stages a Claude id for a brand-new session's
    # first launch. An adopted directory already exists, so its first open is
    # treated as a reopen, and the staged id made it ask to continue a
    # conversation that never existed (the default answer then failed). Drop
    # the id on a first adoption so the first open starts fresh; re-adopted
    # records keep the conversation they name.
    local prior_binding
    prior_binding=$(_read_local_state "$target_dir/.cs/local/state" claude_session_id)
    create_session_structure "$target_dir" "$engine"
    [ -n "$prior_binding" ] || _unset_local_state "$target_dir/.cs/local/state" claude_session_id
    _set_local_state "$target_dir/.cs/local/state" engine "$engine"

    # An adopted session's name is the link's, not the directory's, and the link
    # is the only place it lives — so a hook that resolves this project by
    # walking up from it has nothing to read. Record it where that walk looks
    # (hooks/cs-resolve.sh's _cs_session_name).
    _set_local_state "$target_dir/.cs/local/state" session_name "$session_name"

    # Create symlink from sessions root
    mkdir -p "$SESSIONS_ROOT"
    ln -s "$target_dir" "$session_link"

    # Initialize git if not already a repo. A linked worktree or submodule has
    # a .git file, not a directory; reading that as "no repo" ran the fresh-repo
    # path in the user's checkout (template .gitignore, branch renamed to main).
    if [ ! -e "$target_dir/.git" ]; then
        (
            cd "$target_dir" || exit 0
            create_session_gitignore "$target_dir"
            git init -q 2>/dev/null || true
            # See the session-init path: autocrlf would rewrite .gitignore to
            # CRLF and its patterns would stop matching.
            git config core.autocrlf false 2>/dev/null || true
            git branch -M main 2>/dev/null || true
            setup_merge_attributes "$target_dir"
            git add -A 2>/dev/null || true
            git commit -q -m "Adopt as cs session: $session_name" 2>/dev/null || true
        )
    else
        # Merge cs's .gitignore entries into the project's existing .gitignore
        ensure_cs_gitignore_entries "$target_dir"

        # Commit the adoption
        (
            cd "$target_dir" || exit 0
            setup_merge_attributes "$target_dir"
            git add .cs/ .gitignore .gitattributes 2>/dev/null || true
            # The commit names its own paths: this runs inside the user's
            # project repo, and a bare `git commit` would sweep whatever they
            # had staged into a commit titled "Adopt as cs session". The
            # --cached check is scoped the same way, or a user's unrelated
            # staged file would make cs commit when it has nothing to say.
            # (`git commit -- <paths>` only matches TRACKED paths, so the add
            # above is what makes the new .cs files eligible.)
            if ! git diff --cached --quiet -- .cs/ .gitignore .gitattributes 2>/dev/null; then
                git commit -q -m "Adopt as cs session: $session_name" -- .cs/ .gitignore .gitattributes 2>/dev/null || true
            fi
        )
    fi

    info "Adopted $(basename "$target_dir") as session '$session_name'"
    echo -e "${DIM}Symlink: $session_link -> $target_dir${NC}"
    echo -e "${DIM}Resume with: ags $session_name${NC}"
}

# Uninstall agent-sessions and all components
run_uninstall() {
    local install_dir="${CS_INSTALL_DIR:-$HOME/.local/bin}"
    local install_engines install_config="${CS_INSTALL_DIR:-$HOME/.local/bin}/.cs-install-engines"
    install_engines=$(cat "$install_config" 2>/dev/null) || install_engines=claude,codex
    local hooks_parent_dir="$HOME/.claude/hooks"
    local hooks_dir="$hooks_parent_dir/cs"
    local commands_dir="$HOME/.claude/commands"
    local skills_dir="$HOME/.claude/skills"
    local settings_file="${CS_CLAUDE_DIR:-$HOME/.claude}/settings.json"
    local bash_completion_dir="$HOME/.bash_completion.d"
    # install.sh picks the zsh completion dir from the user's fpath line: its
    # default ~/.zsh/completions, or ~/.zsh/completion when .zshrc spells it
    # singular. install.sh runs as a lone downloaded file with no lib/ on disk,
    # so that detection cannot be shared as code. Rather than mirroring its
    # regex here, sweep BOTH spellings: `~/\.zsh/completions?` can only ever
    # yield those two, so a superset cannot drift with the detection — and it
    # still finds the file when .zshrc was edited after the install.
    # KEEP IN SYNC with install.sh's ZSH_COMPLETION_DIR block: a third candidate
    # there needs an entry here.
    local zsh_completion_dirs=("$HOME/.zsh/completions" "$HOME/.zsh/completion")
    # check_update_notify stamps update-check and update-notes-* here; they
    # outlived a full uninstall and made the next install look up to date.
    local update_cache_dir="${CS_CACHE_DIR:-$HOME/.cache/cs}"

    warn "This will uninstall agent-sessions (ags) and its cs compatibility aliases:"
    echo "  - $install_dir/ags and $install_dir/cs, plus ags/cs companion commands"
    echo "  - Hooks in $hooks_dir/"
    echo "  - Commands in $commands_dir/"
    echo "  - Skills in $skills_dir/"
    echo "  - Shell completions"
    echo "  - Update-check cache in $update_cache_dir/"
    echo "  - Hook entries in $settings_file"
    echo ""
    read -p "Continue with uninstall? [y/N] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        info "Uninstall cancelled."
        return 0
    fi

    echo ""
    info "Uninstalling agent-sessions..."
    echo ""

    # Remove canonical commands and legacy command aliases. `-L` includes a
    # dangling symlink left by an interrupted install or manual binary removal.
    local command_name
    for command_name in ags cs ags-secrets cs-secrets ags-codex-thread cs-codex-thread; do
        if [ -e "$install_dir/$command_name" ] || [ -L "$install_dir/$command_name" ]; then
            rm -f "$install_dir/$command_name"
            info "Removed $install_dir/$command_name"
        fi
    done

    if [[ ",$install_engines," == *,claude,* ]]; then
    for command_name in ags-statusline cs-statusline ags-subagent-statusline cs-subagent-statusline; do
        if [ -e "$install_dir/$command_name" ] || [ -L "$install_dir/$command_name" ]; then
            rm -f "$install_dir/$command_name"
            info "Removed $install_dir/$command_name"
        fi
    done

    # Remove status-line registrations only when they point at either the
    # canonical ags helpers or their legacy cs aliases;
    # a status line the user configured themselves is left untouched.
    if command -v jq >/dev/null 2>&1 && _strip_statusline_registration "$settings_file"; then
        info "Removed agent-sessions statusLine registration from settings.json"
    fi

    # Remove the subagentStatusLine registration only when it points at one of
    # our helper names; a row renderer the user configured is left alone.
    if command -v jq >/dev/null 2>&1 && _strip_subagent_statusline_registration "$settings_file"; then
        info "Removed agent-sessions subagentStatusLine registration from settings.json"
    fi

    rm -f "$(_statusline_declined_marker)"

    fi

    # The .exe name is only ever a leftover from an install that predates
    # dropping Windows; remove it too so an upgrade leaves nothing behind.
    for _tui in ags-tui cs-tui ags-tui.exe cs-tui.exe; do
        if [ -f "$install_dir/$_tui" ]; then
            rm "$install_dir/$_tui"
            info "Removed $install_dir/$_tui"
        fi
    done

    if [[ ",$install_engines," == *,claude,* ]]; then
    # Remove hooks from both deployment layouts (subdirectory and flat)
    local hook dir
    for hook in "${CS_HOOKS[@]}" "${CS_HOOK_LIBS[@]}"; do
        for dir in "$hooks_dir" "$hooks_parent_dir"; do
            if [ -f "$dir/$hook" ]; then
                rm "$dir/$hook"
                info "Removed $dir/$hook"
            fi
        done
    done

    # Remove retired hook files left behind from older cs versions
    local retired
    for retired in "${RETIRED_HOOKS[@]}"; do
        for dir in "$hooks_dir" "$hooks_parent_dir"; do
            if [ -f "$dir/$retired" ]; then
                rm "$dir/$retired"
                info "Removed retired $dir/$retired"
            fi
        done
    done
    rm -f "$hooks_dir/.version"
    rmdir "$hooks_dir" 2>/dev/null || true

    # Remove commands
    for cmd in "${CS_COMMANDS[@]}"; do
        if [ -f "$commands_dir/$cmd" ]; then
            rm "$commands_dir/$cmd"
            info "Removed $commands_dir/$cmd"
        fi
    done

    # Remove skills, current and retired. A machine that never ran an install
    # carrying the rename still has the old directory, so uninstall must clear
    # both lists or it leaves cs files behind.
    local skill
    for skill in "${CS_SKILLS[@]}" "${RETIRED_SKILLS[@]}"; do
        if [ -d "$skills_dir/$skill" ]; then
            rm -rf "$skills_dir/$skill"
            info "Removed $skills_dir/$skill/"
        fi
    done

    # Remove mods: each deploys under its own directory beside the skills.
    # Ownership is by name, as for the skills above: cs deploys these names
    # and removes them whole, extra files included. Do not re-fix.
    local mod_file mod
    for mod_file in "${CS_MOD_FILES[@]}"; do
        mod="${mod_file%%/*}"
        if [ -d "$skills_dir/$mod" ]; then
            rm -rf "$skills_dir/$mod"
            info "Removed $skills_dir/$mod/"
        fi
    done

    fi

    # Remove shell completions
    for _completion in ags.bash cs.bash; do
        if [ -f "$bash_completion_dir/$_completion" ] || [ -L "$bash_completion_dir/$_completion" ]; then
            rm -f "$bash_completion_dir/$_completion"
            info "Removed $bash_completion_dir/$_completion"
        fi
    done

    local zsh_dir
    for zsh_dir in "${zsh_completion_dirs[@]}"; do
        for _completion in _ags _cs; do
            if [ -f "$zsh_dir/$_completion" ] || [ -L "$zsh_dir/$_completion" ]; then
                rm -f "$zsh_dir/$_completion"
                info "Removed $zsh_dir/$_completion"
            fi
        done
    done

    if [ -d "$update_cache_dir" ]; then
        rm -rf "$update_cache_dir"
        info "Removed $update_cache_dir"
    fi

    if [[ ",$install_engines," == *,claude,* ]]; then
    # Clean up settings.json (remove cs hooks, preserve others)
    if [ -f "$settings_file" ] && command -v jq >/dev/null 2>&1; then
        local settings
        settings=$(cat "$settings_file")

        # Strip every cs hook (current and retired) from any event,
        # event-agnostic, matching both path spellings ($HOME and ~) in both
        # deployment layouts (subdirectory and flat). Drops wrappers that
        # empty out; sibling user hooks co-shipped in a wrapper survive.
        local strip_name
        for strip_name in "${CS_HOOKS[@]}" "${RETIRED_HOOKS[@]}"; do
            settings=$(_strip_hook_registration "$settings" "$hooks_dir/$strip_name" "~/.claude/hooks/cs/$strip_name")
            settings=$(_strip_hook_registration "$settings" "$hooks_parent_dir/$strip_name" "~/.claude/hooks/$strip_name")
        done

        # Clean up empty hook arrays
        settings=$(echo "$settings" | jq '
            if .hooks then
                .hooks |= with_entries(select(.value | length > 0))
                | if .hooks == {} then del(.hooks) else . end
            else . end
        ')

        echo "$settings" > "$settings_file"
        info "Cleaned up $settings_file"
    elif [ -f "$settings_file" ]; then
        warn "jq not found - cannot clean up $settings_file automatically"
        warn "Manually remove cs hook entries from $settings_file"
    fi

    fi
    rm -f "$install_config"

    # Ask about secrets in keychain
    if [ -d "$SESSIONS_ROOT" ]; then
        local sessions
        sessions=$(ls -1 "$SESSIONS_ROOT" 2>/dev/null || true)

        if [ -n "$sessions" ]; then
            echo ""
            warn "Secrets may exist in OS keychain for these sessions:"
            echo "$sessions" | while read -r s; do
                echo "  - $s"
            done
            echo ""
            read -p "Delete secrets from keychain? [y/N] " -n 1 -r
            echo ""
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                # Find cs-secrets script
                local secrets_script=""
                for loc in "$install_dir/ags-secrets" "$install_dir/cs-secrets" "/usr/local/bin/ags-secrets" "/usr/local/bin/cs-secrets"; do
                    if [ -x "$loc" ]; then
                        secrets_script="$loc"
                        break
                    fi
                done

                if [ -n "$secrets_script" ]; then
                    echo "$sessions" | while read -r s; do
                        "$secrets_script" --session "$s" purge 2>/dev/null || true
                    done
                else
                    warn "cs-secrets not found - cannot purge secrets automatically"
                fi
            else
                info "Kept secrets in keychain"
            fi
        fi
    fi

    # Ask about session data
    if [ -d "$SESSIONS_ROOT" ]; then
        echo ""
        warn "Session data exists at $SESSIONS_ROOT"
        read -p "Delete session data? This cannot be undone. [y/N] " -n 1 -r
        echo ""
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf "$SESSIONS_ROOT"
            info "Removed $SESSIONS_ROOT"
        else
            info "Kept $SESSIONS_ROOT"
        fi
    fi

    echo ""
    info "Uninstall complete!"
}

# Main function
